ALTER DEFAULT PRIVILEGES IN SCHEMA public
  REVOKE SELECT, INSERT, UPDATE, DELETE ON TABLES FROM jbm_app;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
  REVOKE USAGE, SELECT ON SEQUENCES FROM jbm_app;

REVOKE USAGE ON SCHEMA public FROM jbm_app;

DROP OWNED BY jbm_app;

DROP ROLE IF EXISTS jbm_app;
