// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: activity.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countApprovedAdjustmentsByDay = `-- name: CountApprovedAdjustmentsByDay :many
SELECT date_trunc('day', created_at AT TIME ZONE $2::text)::date AS day, COUNT(*)::bigint AS n
FROM inventory_adjustment_requests
WHERE business_id = $1 AND status = 'approved' AND created_at >= $3 AND created_at < $4
GROUP BY day
`

type CountApprovedAdjustmentsByDayParams struct {
	BusinessID  uuid.UUID          `json:"business_id"`
	Column2     string             `json:"column_2"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CreatedAt_2 pgtype.Timestamptz `json:"created_at_2"`
}

type CountApprovedAdjustmentsByDayRow struct {
	Day pgtype.Date `json:"day"`
	N   int64       `json:"n"`
}

func (q *Queries) CountApprovedAdjustmentsByDay(ctx context.Context, arg CountApprovedAdjustmentsByDayParams) ([]CountApprovedAdjustmentsByDayRow, error) {
	rows, err := q.db.Query(ctx, countApprovedAdjustmentsByDay,
		arg.BusinessID,
		arg.Column2,
		arg.CreatedAt,
		arg.CreatedAt_2,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountApprovedAdjustmentsByDayRow{}
	for rows.Next() {
		var i CountApprovedAdjustmentsByDayRow
		if err := rows.Scan(&i.Day, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countExpensesByDay = `-- name: CountExpensesByDay :many
SELECT date_trunc('day', occurred_at AT TIME ZONE $2::text)::date AS day, COUNT(*)::bigint AS n
FROM expenses WHERE business_id = $1 AND occurred_at >= $3 AND occurred_at < $4
GROUP BY day
`

type CountExpensesByDayParams struct {
	BusinessID   uuid.UUID          `json:"business_id"`
	Column2      string             `json:"column_2"`
	OccurredAt   pgtype.Timestamptz `json:"occurred_at"`
	OccurredAt_2 pgtype.Timestamptz `json:"occurred_at_2"`
}

type CountExpensesByDayRow struct {
	Day pgtype.Date `json:"day"`
	N   int64       `json:"n"`
}

func (q *Queries) CountExpensesByDay(ctx context.Context, arg CountExpensesByDayParams) ([]CountExpensesByDayRow, error) {
	rows, err := q.db.Query(ctx, countExpensesByDay,
		arg.BusinessID,
		arg.Column2,
		arg.OccurredAt,
		arg.OccurredAt_2,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountExpensesByDayRow{}
	for rows.Next() {
		var i CountExpensesByDayRow
		if err := rows.Scan(&i.Day, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countSalesByDay = `-- name: CountSalesByDay :many

SELECT date_trunc('day', occurred_at AT TIME ZONE $2::text)::date AS day, COUNT(*)::bigint AS n
FROM sales WHERE business_id = $1 AND occurred_at >= $3 AND occurred_at < $4
GROUP BY day
`

type CountSalesByDayParams struct {
	BusinessID   uuid.UUID          `json:"business_id"`
	Column2      string             `json:"column_2"`
	OccurredAt   pgtype.Timestamptz `json:"occurred_at"`
	OccurredAt_2 pgtype.Timestamptz `json:"occurred_at_2"`
}

type CountSalesByDayRow struct {
	Day pgtype.Date `json:"day"`
	N   int64       `json:"n"`
}

// The Activity page's GitHub-style daily heatmap needs a per-day count
// across all four activity sources combined. A single UNION-inside-a-CTE
// query feeding a GROUP BY/date_trunc aggregate reliably tripped sqlc's
// static analyzer (a real limitation of the tool, not a Postgres
// correctness issue -- the same UNION shape runs fine as a plain, non-
// aggregated SELECT in ListActivity above). Four separate, single-table
// day-count queries, merged into one day->count map in Go
// (internal/activity), sidestep it entirely and are individually simpler
// to read besides.
func (q *Queries) CountSalesByDay(ctx context.Context, arg CountSalesByDayParams) ([]CountSalesByDayRow, error) {
	rows, err := q.db.Query(ctx, countSalesByDay,
		arg.BusinessID,
		arg.Column2,
		arg.OccurredAt,
		arg.OccurredAt_2,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountSalesByDayRow{}
	for rows.Next() {
		var i CountSalesByDayRow
		if err := rows.Scan(&i.Day, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countStockReceiptsByDay = `-- name: CountStockReceiptsByDay :many
SELECT date_trunc('day', received_at AT TIME ZONE $2::text)::date AS day, COUNT(*)::bigint AS n
FROM stock_receipts WHERE business_id = $1 AND received_at >= $3 AND received_at < $4
GROUP BY day
`

type CountStockReceiptsByDayParams struct {
	BusinessID   uuid.UUID          `json:"business_id"`
	Column2      string             `json:"column_2"`
	ReceivedAt   pgtype.Timestamptz `json:"received_at"`
	ReceivedAt_2 pgtype.Timestamptz `json:"received_at_2"`
}

type CountStockReceiptsByDayRow struct {
	Day pgtype.Date `json:"day"`
	N   int64       `json:"n"`
}

func (q *Queries) CountStockReceiptsByDay(ctx context.Context, arg CountStockReceiptsByDayParams) ([]CountStockReceiptsByDayRow, error) {
	rows, err := q.db.Query(ctx, countStockReceiptsByDay,
		arg.BusinessID,
		arg.Column2,
		arg.ReceivedAt,
		arg.ReceivedAt_2,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountStockReceiptsByDayRow{}
	for rows.Next() {
		var i CountStockReceiptsByDayRow
		if err := rows.Scan(&i.Day, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActivity = `-- name: ListActivity :many
WITH feed AS (
    SELECT
        s.id, 'sale' AS type, s.seller_id AS actor_id, s.occurred_at,
        CASE WHEN s.reversal_of_sale_id IS NOT NULL THEN 'Sale reversed' ELSE 'Sale recorded' END AS summary,
        s.total_kobo AS amount_kobo
    FROM sales s WHERE s.business_id = $1
    UNION ALL
    SELECT
        e.id, 'expense' AS type, e.recorded_by AS actor_id, e.occurred_at,
        CASE WHEN e.reversal_of_expense_id IS NOT NULL THEN 'Expense reversed' ELSE e.description END AS summary,
        -e.amount_kobo AS amount_kobo
    FROM expenses e WHERE e.business_id = $2
    UNION ALL
    SELECT
        r.id, 'inventory_adjustment' AS type, r.requested_by AS actor_id, r.created_at AS occurred_at,
        r.reason_category || ': ' || r.reason_note AS summary,
        0::bigint AS amount_kobo
    FROM inventory_adjustment_requests r
    WHERE r.business_id = $3 AND r.status = 'approved'
    UNION ALL
    SELECT
        sr.id, 'stock_receipt' AS type, sr.received_by AS actor_id, sr.received_at AS occurred_at,
        'Stock received' AS summary,
        -COALESCE((SELECT SUM(l.total_cost_kobo) FROM stock_receipt_lines l WHERE l.receipt_id = sr.id), 0)::bigint AS amount_kobo
    FROM stock_receipts sr WHERE sr.business_id = $4
)
SELECT id, type, actor_id, occurred_at, summary, amount_kobo FROM feed
WHERE ($5::uuid IS NULL OR actor_id = $5)
  AND ($6::text IS NULL OR type = $6)
  AND ($7::timestamptz IS NULL OR occurred_at >= $7)
  AND ($8::timestamptz IS NULL OR occurred_at < $8)
ORDER BY occurred_at DESC
LIMIT $9
`

type ListActivityParams struct {
	BusinessID   uuid.UUID          `json:"business_id"`
	BusinessID_2 uuid.UUID          `json:"business_id_2"`
	BusinessID_3 uuid.UUID          `json:"business_id_3"`
	BusinessID_4 uuid.UUID          `json:"business_id_4"`
	ActorID      pgtype.UUID        `json:"actor_id"`
	ActivityType pgtype.Text        `json:"activity_type"`
	StartAt      pgtype.Timestamptz `json:"start_at"`
	EndAt        pgtype.Timestamptz `json:"end_at"`
	RowLimit     int32              `json:"row_limit"`
}

type ListActivityRow struct {
	ID         uuid.UUID          `json:"id"`
	Type       string             `json:"type"`
	ActorID    uuid.UUID          `json:"actor_id"`
	OccurredAt pgtype.Timestamptz `json:"occurred_at"`
	Summary    string             `json:"summary"`
	AmountKobo int64              `json:"amount_kobo"`
}

// Unified activity feed (docs/PHASE_EXPENSES_DASHBOARD_ACTIVITY_REPORTS.md
// §3): a query-time UNION ALL across every domain's own already-posted
// records, not a new activity_events writer table -- deliberately, same
// reasoning that kept this codebase off the generic review_cases table
// and the generic Phase 4 sync protocol. amount_kobo is framed as cash
// impact (positive = money in, negative = money out) rather than each
// table's own storage sign convention -- a sale's total_kobo is already
// money-in-positive, but an expense's amount_kobo (positive = money out
// by storage convention, negative for its reversal) is flipped here so
// every row in this feed means the same thing. Every branch aliases its
// table and qualifies every column (even business_id) explicitly --
// sqlc's static analyzer otherwise reports a false-positive "business_id
// is ambiguous" on a UNION ALL of several tables that all happen to carry
// that column, even though each branch's own FROM is unambiguous under
// real Postgres.
func (q *Queries) ListActivity(ctx context.Context, arg ListActivityParams) ([]ListActivityRow, error) {
	rows, err := q.db.Query(ctx, listActivity,
		arg.BusinessID,
		arg.BusinessID_2,
		arg.BusinessID_3,
		arg.BusinessID_4,
		arg.ActorID,
		arg.ActivityType,
		arg.StartAt,
		arg.EndAt,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActivityRow{}
	for rows.Next() {
		var i ListActivityRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.ActorID,
			&i.OccurredAt,
			&i.Summary,
			&i.AmountKobo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
