// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: activity_flags.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createActivityFlag = `-- name: CreateActivityFlag :one
INSERT INTO activity_flags (id, business_id, source_type, source_id, flagged_by, reason)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, business_id, source_type, source_id, flagged_by, reason, status, resolved_by, resolution_note, created_at, resolved_at
`

type CreateActivityFlagParams struct {
	ID         uuid.UUID `json:"id"`
	BusinessID uuid.UUID `json:"business_id"`
	SourceType string    `json:"source_type"`
	SourceID   uuid.UUID `json:"source_id"`
	FlaggedBy  uuid.UUID `json:"flagged_by"`
	Reason     string    `json:"reason"`
}

func (q *Queries) CreateActivityFlag(ctx context.Context, arg CreateActivityFlagParams) (ActivityFlag, error) {
	row := q.db.QueryRow(ctx, createActivityFlag,
		arg.ID,
		arg.BusinessID,
		arg.SourceType,
		arg.SourceID,
		arg.FlaggedBy,
		arg.Reason,
	)
	var i ActivityFlag
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.SourceType,
		&i.SourceID,
		&i.FlaggedBy,
		&i.Reason,
		&i.Status,
		&i.ResolvedBy,
		&i.ResolutionNote,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const getActivityFlagByID = `-- name: GetActivityFlagByID :one
SELECT id, business_id, source_type, source_id, flagged_by, reason, status, resolved_by, resolution_note, created_at, resolved_at FROM activity_flags WHERE business_id = $1 AND id = $2
`

type GetActivityFlagByIDParams struct {
	BusinessID uuid.UUID `json:"business_id"`
	ID         uuid.UUID `json:"id"`
}

func (q *Queries) GetActivityFlagByID(ctx context.Context, arg GetActivityFlagByIDParams) (ActivityFlag, error) {
	row := q.db.QueryRow(ctx, getActivityFlagByID, arg.BusinessID, arg.ID)
	var i ActivityFlag
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.SourceType,
		&i.SourceID,
		&i.FlaggedBy,
		&i.Reason,
		&i.Status,
		&i.ResolvedBy,
		&i.ResolutionNote,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const listOpenActivityFlags = `-- name: ListOpenActivityFlags :many
SELECT id, business_id, source_type, source_id, flagged_by, reason, status, resolved_by, resolution_note, created_at, resolved_at FROM activity_flags WHERE business_id = $1 AND status = 'open' ORDER BY created_at DESC
`

func (q *Queries) ListOpenActivityFlags(ctx context.Context, businessID uuid.UUID) ([]ActivityFlag, error) {
	rows, err := q.db.Query(ctx, listOpenActivityFlags, businessID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ActivityFlag{}
	for rows.Next() {
		var i ActivityFlag
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.SourceType,
			&i.SourceID,
			&i.FlaggedBy,
			&i.Reason,
			&i.Status,
			&i.ResolvedBy,
			&i.ResolutionNote,
			&i.CreatedAt,
			&i.ResolvedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveActivityFlag = `-- name: ResolveActivityFlag :one
UPDATE activity_flags
SET status = 'resolved', resolved_by = $3, resolved_at = now(), resolution_note = $4
WHERE business_id = $1 AND id = $2 AND status = 'open'
RETURNING id, business_id, source_type, source_id, flagged_by, reason, status, resolved_by, resolution_note, created_at, resolved_at
`

type ResolveActivityFlagParams struct {
	BusinessID     uuid.UUID   `json:"business_id"`
	ID             uuid.UUID   `json:"id"`
	ResolvedBy     pgtype.UUID `json:"resolved_by"`
	ResolutionNote pgtype.Text `json:"resolution_note"`
}

func (q *Queries) ResolveActivityFlag(ctx context.Context, arg ResolveActivityFlagParams) (ActivityFlag, error) {
	row := q.db.QueryRow(ctx, resolveActivityFlag,
		arg.BusinessID,
		arg.ID,
		arg.ResolvedBy,
		arg.ResolutionNote,
	)
	var i ActivityFlag
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.SourceType,
		&i.SourceID,
		&i.FlaggedBy,
		&i.Reason,
		&i.Status,
		&i.ResolvedBy,
		&i.ResolutionNote,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}
