// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bill_share_links.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getActiveBillShareLinkByTokenHash = `-- name: GetActiveBillShareLinkByTokenHash :one
SELECT id, business_id, bill_id, token_hash, created_by, created_at, expires_at, revoked_at FROM bill_share_links
WHERE token_hash = $1 AND revoked_at IS NULL AND (expires_at IS NULL OR expires_at > now())
`

func (q *Queries) GetActiveBillShareLinkByTokenHash(ctx context.Context, tokenHash string) (BillShareLink, error) {
	row := q.db.QueryRow(ctx, getActiveBillShareLinkByTokenHash, tokenHash)
	var i BillShareLink
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.BillID,
		&i.TokenHash,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const revokeBillShareLinkByBillID = `-- name: RevokeBillShareLinkByBillID :one
UPDATE bill_share_links
SET revoked_at = now()
WHERE business_id = $1 AND bill_id = $2 AND revoked_at IS NULL
RETURNING id, business_id, bill_id, token_hash, created_by, created_at, expires_at, revoked_at
`

type RevokeBillShareLinkByBillIDParams struct {
	BusinessID uuid.UUID `json:"business_id"`
	BillID     uuid.UUID `json:"bill_id"`
}

func (q *Queries) RevokeBillShareLinkByBillID(ctx context.Context, arg RevokeBillShareLinkByBillIDParams) (BillShareLink, error) {
	row := q.db.QueryRow(ctx, revokeBillShareLinkByBillID, arg.BusinessID, arg.BillID)
	var i BillShareLink
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.BillID,
		&i.TokenHash,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const upsertBillShareLink = `-- name: UpsertBillShareLink :one
INSERT INTO bill_share_links (id, business_id, bill_id, token_hash, created_by, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (bill_id) DO UPDATE
    SET token_hash = EXCLUDED.token_hash,
        created_by = EXCLUDED.created_by,
        created_at = now(),
        expires_at = EXCLUDED.expires_at,
        revoked_at = NULL
RETURNING id, business_id, bill_id, token_hash, created_by, created_at, expires_at, revoked_at
`

type UpsertBillShareLinkParams struct {
	ID         uuid.UUID          `json:"id"`
	BusinessID uuid.UUID          `json:"business_id"`
	BillID     uuid.UUID          `json:"bill_id"`
	TokenHash  string             `json:"token_hash"`
	CreatedBy  uuid.UUID          `json:"created_by"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) UpsertBillShareLink(ctx context.Context, arg UpsertBillShareLinkParams) (BillShareLink, error) {
	row := q.db.QueryRow(ctx, upsertBillShareLink,
		arg.ID,
		arg.BusinessID,
		arg.BillID,
		arg.TokenHash,
		arg.CreatedBy,
		arg.ExpiresAt,
	)
	var i BillShareLink
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.BillID,
		&i.TokenHash,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}
