// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: businesses.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createBusiness = `-- name: CreateBusiness :one
INSERT INTO businesses (id, name)
VALUES ($1, $2)
RETURNING id, name, timezone, currency, phone, address, receipt_wording, receipt_footer, payment_instructions, logo_object_key, status, created_at, updated_at
`

type CreateBusinessParams struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

func (q *Queries) CreateBusiness(ctx context.Context, arg CreateBusinessParams) (Business, error) {
	row := q.db.QueryRow(ctx, createBusiness, arg.ID, arg.Name)
	var i Business
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Timezone,
		&i.Currency,
		&i.Phone,
		&i.Address,
		&i.ReceiptWording,
		&i.ReceiptFooter,
		&i.PaymentInstructions,
		&i.LogoObjectKey,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBusinessByID = `-- name: GetBusinessByID :one
SELECT id, name, timezone, currency, phone, address, receipt_wording, receipt_footer, payment_instructions, logo_object_key, status, created_at, updated_at FROM businesses WHERE id = $1
`

func (q *Queries) GetBusinessByID(ctx context.Context, id uuid.UUID) (Business, error) {
	row := q.db.QueryRow(ctx, getBusinessByID, id)
	var i Business
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Timezone,
		&i.Currency,
		&i.Phone,
		&i.Address,
		&i.ReceiptWording,
		&i.ReceiptFooter,
		&i.PaymentInstructions,
		&i.LogoObjectKey,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
