// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: catalogue_templates.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const listCatalogueTemplateVariantsByTemplateIDs = `-- name: ListCatalogueTemplateVariantsByTemplateIDs :many
SELECT id, template_id, name, suggested_price_kobo, sort_order, created_at FROM catalogue_template_variants
WHERE template_id = ANY($1::uuid[])
ORDER BY template_id, sort_order, name
`

func (q *Queries) ListCatalogueTemplateVariantsByTemplateIDs(ctx context.Context, templateIds []uuid.UUID) ([]CatalogueTemplateVariant, error) {
	rows, err := q.db.Query(ctx, listCatalogueTemplateVariantsByTemplateIDs, templateIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CatalogueTemplateVariant{}
	for rows.Next() {
		var i CatalogueTemplateVariant
		if err := rows.Scan(
			&i.ID,
			&i.TemplateID,
			&i.Name,
			&i.SuggestedPriceKobo,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCatalogueTemplates = `-- name: ListCatalogueTemplates :many
SELECT id, name, category_name, sort_order, created_at FROM catalogue_templates ORDER BY sort_order, name
`

func (q *Queries) ListCatalogueTemplates(ctx context.Context) ([]CatalogueTemplate, error) {
	rows, err := q.db.Query(ctx, listCatalogueTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CatalogueTemplate{}
	for rows.Next() {
		var i CatalogueTemplate
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CategoryName,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCatalogueTemplatesByIDs = `-- name: ListCatalogueTemplatesByIDs :many
SELECT id, name, category_name, sort_order, created_at FROM catalogue_templates WHERE id = ANY($1::uuid[]) ORDER BY sort_order, name
`

func (q *Queries) ListCatalogueTemplatesByIDs(ctx context.Context, ids []uuid.UUID) ([]CatalogueTemplate, error) {
	rows, err := q.db.Query(ctx, listCatalogueTemplatesByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CatalogueTemplate{}
	for rows.Next() {
		var i CatalogueTemplate
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CategoryName,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCatalogueTemplate = `-- name: UpsertCatalogueTemplate :one
INSERT INTO catalogue_templates (id, name, category_name, sort_order)
VALUES ($1, $2, $3, $4)
ON CONFLICT (name) DO UPDATE
    SET category_name = EXCLUDED.category_name, sort_order = EXCLUDED.sort_order
RETURNING id, name, category_name, sort_order, created_at
`

type UpsertCatalogueTemplateParams struct {
	ID           uuid.UUID `json:"id"`
	Name         string    `json:"name"`
	CategoryName string    `json:"category_name"`
	SortOrder    int32     `json:"sort_order"`
}

func (q *Queries) UpsertCatalogueTemplate(ctx context.Context, arg UpsertCatalogueTemplateParams) (CatalogueTemplate, error) {
	row := q.db.QueryRow(ctx, upsertCatalogueTemplate,
		arg.ID,
		arg.Name,
		arg.CategoryName,
		arg.SortOrder,
	)
	var i CatalogueTemplate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CategoryName,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const upsertCatalogueTemplateVariant = `-- name: UpsertCatalogueTemplateVariant :one
INSERT INTO catalogue_template_variants (id, template_id, name, suggested_price_kobo, sort_order)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (template_id, name) DO UPDATE
    SET suggested_price_kobo = EXCLUDED.suggested_price_kobo, sort_order = EXCLUDED.sort_order
RETURNING id, template_id, name, suggested_price_kobo, sort_order, created_at
`

type UpsertCatalogueTemplateVariantParams struct {
	ID                 uuid.UUID `json:"id"`
	TemplateID         uuid.UUID `json:"template_id"`
	Name               string    `json:"name"`
	SuggestedPriceKobo int64     `json:"suggested_price_kobo"`
	SortOrder          int32     `json:"sort_order"`
}

func (q *Queries) UpsertCatalogueTemplateVariant(ctx context.Context, arg UpsertCatalogueTemplateVariantParams) (CatalogueTemplateVariant, error) {
	row := q.db.QueryRow(ctx, upsertCatalogueTemplateVariant,
		arg.ID,
		arg.TemplateID,
		arg.Name,
		arg.SuggestedPriceKobo,
		arg.SortOrder,
	)
	var i CatalogueTemplateVariant
	err := row.Scan(
		&i.ID,
		&i.TemplateID,
		&i.Name,
		&i.SuggestedPriceKobo,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}
