// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: categories.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (id, business_id, name, sort_order)
VALUES ($1, $2, $3, $4)
RETURNING id, business_id, name, sort_order, active, created_at, updated_at
`

type CreateCategoryParams struct {
	ID         uuid.UUID `json:"id"`
	BusinessID uuid.UUID `json:"business_id"`
	Name       string    `json:"name"`
	SortOrder  int32     `json:"sort_order"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory,
		arg.ID,
		arg.BusinessID,
		arg.Name,
		arg.SortOrder,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Name,
		&i.SortOrder,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCategoryByID = `-- name: GetCategoryByID :one
SELECT id, business_id, name, sort_order, active, created_at, updated_at FROM categories WHERE business_id = $1 AND id = $2
`

type GetCategoryByIDParams struct {
	BusinessID uuid.UUID `json:"business_id"`
	ID         uuid.UUID `json:"id"`
}

func (q *Queries) GetCategoryByID(ctx context.Context, arg GetCategoryByIDParams) (Category, error) {
	row := q.db.QueryRow(ctx, getCategoryByID, arg.BusinessID, arg.ID)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Name,
		&i.SortOrder,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCategoryByName = `-- name: GetCategoryByName :one
SELECT id, business_id, name, sort_order, active, created_at, updated_at FROM categories WHERE business_id = $1 AND name = $2
`

type GetCategoryByNameParams struct {
	BusinessID uuid.UUID `json:"business_id"`
	Name       string    `json:"name"`
}

func (q *Queries) GetCategoryByName(ctx context.Context, arg GetCategoryByNameParams) (Category, error) {
	row := q.db.QueryRow(ctx, getCategoryByName, arg.BusinessID, arg.Name)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Name,
		&i.SortOrder,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCategories = `-- name: ListCategories :many
SELECT id, business_id, name, sort_order, active, created_at, updated_at FROM categories WHERE business_id = $1 ORDER BY sort_order, name
`

func (q *Queries) ListCategories(ctx context.Context, businessID uuid.UUID) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategories, businessID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.Name,
			&i.SortOrder,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE categories
SET name = $3, sort_order = $4, active = $5, updated_at = now()
WHERE business_id = $1 AND id = $2
RETURNING id, business_id, name, sort_order, active, created_at, updated_at
`

type UpdateCategoryParams struct {
	BusinessID uuid.UUID `json:"business_id"`
	ID         uuid.UUID `json:"id"`
	Name       string    `json:"name"`
	SortOrder  int32     `json:"sort_order"`
	Active     bool      `json:"active"`
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, updateCategory,
		arg.BusinessID,
		arg.ID,
		arg.Name,
		arg.SortOrder,
		arg.Active,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Name,
		&i.SortOrder,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
