// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: devices.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createDevice = `-- name: CreateDevice :one
INSERT INTO devices (id, business_id, user_id, location_id, public_key, display_name)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, business_id, user_id, location_id, public_key, display_name, status, enrolled_at, last_sync_at, revoked_at, created_at, updated_at
`

type CreateDeviceParams struct {
	ID          uuid.UUID `json:"id"`
	BusinessID  uuid.UUID `json:"business_id"`
	UserID      uuid.UUID `json:"user_id"`
	LocationID  uuid.UUID `json:"location_id"`
	PublicKey   string    `json:"public_key"`
	DisplayName string    `json:"display_name"`
}

func (q *Queries) CreateDevice(ctx context.Context, arg CreateDeviceParams) (Device, error) {
	row := q.db.QueryRow(ctx, createDevice,
		arg.ID,
		arg.BusinessID,
		arg.UserID,
		arg.LocationID,
		arg.PublicKey,
		arg.DisplayName,
	)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.UserID,
		&i.LocationID,
		&i.PublicKey,
		&i.DisplayName,
		&i.Status,
		&i.EnrolledAt,
		&i.LastSyncAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDeviceByID = `-- name: GetDeviceByID :one
SELECT id, business_id, user_id, location_id, public_key, display_name, status, enrolled_at, last_sync_at, revoked_at, created_at, updated_at FROM devices WHERE business_id = $1 AND id = $2
`

type GetDeviceByIDParams struct {
	BusinessID uuid.UUID `json:"business_id"`
	ID         uuid.UUID `json:"id"`
}

func (q *Queries) GetDeviceByID(ctx context.Context, arg GetDeviceByIDParams) (Device, error) {
	row := q.db.QueryRow(ctx, getDeviceByID, arg.BusinessID, arg.ID)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.UserID,
		&i.LocationID,
		&i.PublicKey,
		&i.DisplayName,
		&i.Status,
		&i.EnrolledAt,
		&i.LastSyncAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDevicesForBusiness = `-- name: ListDevicesForBusiness :many
SELECT id, business_id, user_id, location_id, public_key, display_name, status, enrolled_at, last_sync_at, revoked_at, created_at, updated_at FROM devices WHERE business_id = $1 ORDER BY enrolled_at DESC
`

func (q *Queries) ListDevicesForBusiness(ctx context.Context, businessID uuid.UUID) ([]Device, error) {
	rows, err := q.db.Query(ctx, listDevicesForBusiness, businessID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Device{}
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.UserID,
			&i.LocationID,
			&i.PublicKey,
			&i.DisplayName,
			&i.Status,
			&i.EnrolledAt,
			&i.LastSyncAt,
			&i.RevokedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeDevice = `-- name: RevokeDevice :one
UPDATE devices
SET status = 'revoked', revoked_at = now(), updated_at = now()
WHERE business_id = $1 AND id = $2 AND status = 'active'
RETURNING id, business_id, user_id, location_id, public_key, display_name, status, enrolled_at, last_sync_at, revoked_at, created_at, updated_at
`

type RevokeDeviceParams struct {
	BusinessID uuid.UUID `json:"business_id"`
	ID         uuid.UUID `json:"id"`
}

func (q *Queries) RevokeDevice(ctx context.Context, arg RevokeDeviceParams) (Device, error) {
	row := q.db.QueryRow(ctx, revokeDevice, arg.BusinessID, arg.ID)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.UserID,
		&i.LocationID,
		&i.PublicKey,
		&i.DisplayName,
		&i.Status,
		&i.EnrolledAt,
		&i.LastSyncAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
