// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: expenses.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createExpense = `-- name: CreateExpense :one
INSERT INTO expenses
    (id, business_id, location_id, category_id, description, amount_kobo, payment_method, recorded_by, idempotency_key, occurred_at, reversal_of_expense_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, business_id, location_id, category_id, description, amount_kobo, payment_method, recorded_by, idempotency_key, occurred_at, reversal_of_expense_id, created_at
`

type CreateExpenseParams struct {
	ID                  uuid.UUID          `json:"id"`
	BusinessID          uuid.UUID          `json:"business_id"`
	LocationID          uuid.UUID          `json:"location_id"`
	CategoryID          uuid.UUID          `json:"category_id"`
	Description         string             `json:"description"`
	AmountKobo          int64              `json:"amount_kobo"`
	PaymentMethod       string             `json:"payment_method"`
	RecordedBy          uuid.UUID          `json:"recorded_by"`
	IdempotencyKey      uuid.UUID          `json:"idempotency_key"`
	OccurredAt          pgtype.Timestamptz `json:"occurred_at"`
	ReversalOfExpenseID pgtype.UUID        `json:"reversal_of_expense_id"`
}

func (q *Queries) CreateExpense(ctx context.Context, arg CreateExpenseParams) (Expense, error) {
	row := q.db.QueryRow(ctx, createExpense,
		arg.ID,
		arg.BusinessID,
		arg.LocationID,
		arg.CategoryID,
		arg.Description,
		arg.AmountKobo,
		arg.PaymentMethod,
		arg.RecordedBy,
		arg.IdempotencyKey,
		arg.OccurredAt,
		arg.ReversalOfExpenseID,
	)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.LocationID,
		&i.CategoryID,
		&i.Description,
		&i.AmountKobo,
		&i.PaymentMethod,
		&i.RecordedBy,
		&i.IdempotencyKey,
		&i.OccurredAt,
		&i.ReversalOfExpenseID,
		&i.CreatedAt,
	)
	return i, err
}

const createExpenseCategory = `-- name: CreateExpenseCategory :one
INSERT INTO expense_categories (id, business_id, name)
VALUES ($1, $2, $3)
RETURNING id, business_id, name, active, created_at, updated_at
`

type CreateExpenseCategoryParams struct {
	ID         uuid.UUID `json:"id"`
	BusinessID uuid.UUID `json:"business_id"`
	Name       string    `json:"name"`
}

func (q *Queries) CreateExpenseCategory(ctx context.Context, arg CreateExpenseCategoryParams) (ExpenseCategory, error) {
	row := q.db.QueryRow(ctx, createExpenseCategory, arg.ID, arg.BusinessID, arg.Name)
	var i ExpenseCategory
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Name,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getExpenseByID = `-- name: GetExpenseByID :one
SELECT id, business_id, location_id, category_id, description, amount_kobo, payment_method, recorded_by, idempotency_key, occurred_at, reversal_of_expense_id, created_at FROM expenses WHERE business_id = $1 AND id = $2
`

type GetExpenseByIDParams struct {
	BusinessID uuid.UUID `json:"business_id"`
	ID         uuid.UUID `json:"id"`
}

func (q *Queries) GetExpenseByID(ctx context.Context, arg GetExpenseByIDParams) (Expense, error) {
	row := q.db.QueryRow(ctx, getExpenseByID, arg.BusinessID, arg.ID)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.LocationID,
		&i.CategoryID,
		&i.Description,
		&i.AmountKobo,
		&i.PaymentMethod,
		&i.RecordedBy,
		&i.IdempotencyKey,
		&i.OccurredAt,
		&i.ReversalOfExpenseID,
		&i.CreatedAt,
	)
	return i, err
}

const getExpenseByIdempotencyKey = `-- name: GetExpenseByIdempotencyKey :one
SELECT id, business_id, location_id, category_id, description, amount_kobo, payment_method, recorded_by, idempotency_key, occurred_at, reversal_of_expense_id, created_at FROM expenses WHERE business_id = $1 AND idempotency_key = $2
`

type GetExpenseByIdempotencyKeyParams struct {
	BusinessID     uuid.UUID `json:"business_id"`
	IdempotencyKey uuid.UUID `json:"idempotency_key"`
}

func (q *Queries) GetExpenseByIdempotencyKey(ctx context.Context, arg GetExpenseByIdempotencyKeyParams) (Expense, error) {
	row := q.db.QueryRow(ctx, getExpenseByIdempotencyKey, arg.BusinessID, arg.IdempotencyKey)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.LocationID,
		&i.CategoryID,
		&i.Description,
		&i.AmountKobo,
		&i.PaymentMethod,
		&i.RecordedBy,
		&i.IdempotencyKey,
		&i.OccurredAt,
		&i.ReversalOfExpenseID,
		&i.CreatedAt,
	)
	return i, err
}

const getExpenseCategoryByName = `-- name: GetExpenseCategoryByName :one
SELECT id, business_id, name, active, created_at, updated_at FROM expense_categories WHERE business_id = $1 AND name = $2
`

type GetExpenseCategoryByNameParams struct {
	BusinessID uuid.UUID `json:"business_id"`
	Name       string    `json:"name"`
}

func (q *Queries) GetExpenseCategoryByName(ctx context.Context, arg GetExpenseCategoryByNameParams) (ExpenseCategory, error) {
	row := q.db.QueryRow(ctx, getExpenseCategoryByName, arg.BusinessID, arg.Name)
	var i ExpenseCategory
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Name,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getReversalOfExpense = `-- name: GetReversalOfExpense :one
SELECT id, business_id, location_id, category_id, description, amount_kobo, payment_method, recorded_by, idempotency_key, occurred_at, reversal_of_expense_id, created_at FROM expenses WHERE business_id = $1 AND reversal_of_expense_id = $2
`

type GetReversalOfExpenseParams struct {
	BusinessID          uuid.UUID   `json:"business_id"`
	ReversalOfExpenseID pgtype.UUID `json:"reversal_of_expense_id"`
}

func (q *Queries) GetReversalOfExpense(ctx context.Context, arg GetReversalOfExpenseParams) (Expense, error) {
	row := q.db.QueryRow(ctx, getReversalOfExpense, arg.BusinessID, arg.ReversalOfExpenseID)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.LocationID,
		&i.CategoryID,
		&i.Description,
		&i.AmountKobo,
		&i.PaymentMethod,
		&i.RecordedBy,
		&i.IdempotencyKey,
		&i.OccurredAt,
		&i.ReversalOfExpenseID,
		&i.CreatedAt,
	)
	return i, err
}

const listExpenseCategories = `-- name: ListExpenseCategories :many
SELECT id, business_id, name, active, created_at, updated_at FROM expense_categories WHERE business_id = $1 AND active ORDER BY name
`

func (q *Queries) ListExpenseCategories(ctx context.Context, businessID uuid.UUID) ([]ExpenseCategory, error) {
	rows, err := q.db.Query(ctx, listExpenseCategories, businessID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExpenseCategory{}
	for rows.Next() {
		var i ExpenseCategory
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.Name,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpensesDetailed = `-- name: ListExpensesDetailed :many
SELECT
    e.id, e.location_id, e.category_id, e.description, e.amount_kobo, e.payment_method,
    e.recorded_by, e.reversal_of_expense_id, e.occurred_at, e.created_at,
    c.name AS category_name
FROM expenses e
JOIN expense_categories c ON c.business_id = e.business_id AND c.id = e.category_id
WHERE e.business_id = $1
ORDER BY e.occurred_at DESC
LIMIT $2
`

type ListExpensesDetailedParams struct {
	BusinessID uuid.UUID `json:"business_id"`
	Limit      int32     `json:"limit"`
}

type ListExpensesDetailedRow struct {
	ID                  uuid.UUID          `json:"id"`
	LocationID          uuid.UUID          `json:"location_id"`
	CategoryID          uuid.UUID          `json:"category_id"`
	Description         string             `json:"description"`
	AmountKobo          int64              `json:"amount_kobo"`
	PaymentMethod       string             `json:"payment_method"`
	RecordedBy          uuid.UUID          `json:"recorded_by"`
	ReversalOfExpenseID pgtype.UUID        `json:"reversal_of_expense_id"`
	OccurredAt          pgtype.Timestamptz `json:"occurred_at"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	CategoryName        string             `json:"category_name"`
}

func (q *Queries) ListExpensesDetailed(ctx context.Context, arg ListExpensesDetailedParams) ([]ListExpensesDetailedRow, error) {
	rows, err := q.db.Query(ctx, listExpensesDetailed, arg.BusinessID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExpensesDetailedRow{}
	for rows.Next() {
		var i ListExpensesDetailedRow
		if err := rows.Scan(
			&i.ID,
			&i.LocationID,
			&i.CategoryID,
			&i.Description,
			&i.AmountKobo,
			&i.PaymentMethod,
			&i.RecordedBy,
			&i.ReversalOfExpenseID,
			&i.OccurredAt,
			&i.CreatedAt,
			&i.CategoryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumExpensesTotalSince = `-- name: SumExpensesTotalSince :one
SELECT
    COALESCE(SUM(amount_kobo), 0)::bigint AS total,
    COUNT(*) FILTER (WHERE reversal_of_expense_id IS NULL)::bigint AS count
FROM expenses WHERE business_id = $1 AND occurred_at >= $2
`

type SumExpensesTotalSinceParams struct {
	BusinessID uuid.UUID          `json:"business_id"`
	OccurredAt pgtype.Timestamptz `json:"occurred_at"`
}

type SumExpensesTotalSinceRow struct {
	Total int64 `json:"total"`
	Count int64 `json:"count"`
}

// Mirrors SumSalesTotalSince exactly: total nets every row including
// reversals (a reversal's amount_kobo is negative by construction, same
// sign convention as sales.total_kobo); count excludes reversal rows.
func (q *Queries) SumExpensesTotalSince(ctx context.Context, arg SumExpensesTotalSinceParams) (SumExpensesTotalSinceRow, error) {
	row := q.db.QueryRow(ctx, sumExpensesTotalSince, arg.BusinessID, arg.OccurredAt)
	var i SumExpensesTotalSinceRow
	err := row.Scan(&i.Total, &i.Count)
	return i, err
}
