// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identity_verifications.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createIdentityVerification = `-- name: CreateIdentityVerification :one
INSERT INTO identity_verifications (id, user_id, channel, identifier, otp_hash, purpose, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, channel, identifier, otp_hash, purpose, attempts, expires_at, created_at
`

type CreateIdentityVerificationParams struct {
	ID         uuid.UUID          `json:"id"`
	UserID     uuid.UUID          `json:"user_id"`
	Channel    string             `json:"channel"`
	Identifier string             `json:"identifier"`
	OtpHash    string             `json:"otp_hash"`
	Purpose    string             `json:"purpose"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateIdentityVerification(ctx context.Context, arg CreateIdentityVerificationParams) (IdentityVerification, error) {
	row := q.db.QueryRow(ctx, createIdentityVerification,
		arg.ID,
		arg.UserID,
		arg.Channel,
		arg.Identifier,
		arg.OtpHash,
		arg.Purpose,
		arg.ExpiresAt,
	)
	var i IdentityVerification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Channel,
		&i.Identifier,
		&i.OtpHash,
		&i.Purpose,
		&i.Attempts,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteIdentityVerification = `-- name: DeleteIdentityVerification :exec
DELETE FROM identity_verifications WHERE id = $1
`

func (q *Queries) DeleteIdentityVerification(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteIdentityVerification, id)
	return err
}

const getIdentityVerificationByID = `-- name: GetIdentityVerificationByID :one
SELECT id, user_id, channel, identifier, otp_hash, purpose, attempts, expires_at, created_at FROM identity_verifications WHERE id = $1
`

func (q *Queries) GetIdentityVerificationByID(ctx context.Context, id uuid.UUID) (IdentityVerification, error) {
	row := q.db.QueryRow(ctx, getIdentityVerificationByID, id)
	var i IdentityVerification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Channel,
		&i.Identifier,
		&i.OtpHash,
		&i.Purpose,
		&i.Attempts,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const incrementIdentityVerificationAttempts = `-- name: IncrementIdentityVerificationAttempts :exec
UPDATE identity_verifications SET attempts = attempts + 1 WHERE id = $1
`

func (q *Queries) IncrementIdentityVerificationAttempts(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, incrementIdentityVerificationAttempts, id)
	return err
}
