// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: inventory.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createInventoryEvent = `-- name: CreateInventoryEvent :one
INSERT INTO inventory_events (id, business_id, type, actor_id, receipt_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, business_id, type, actor_id, receipt_id, occurred_at, created_at
`

type CreateInventoryEventParams struct {
	ID         uuid.UUID   `json:"id"`
	BusinessID uuid.UUID   `json:"business_id"`
	Type       string      `json:"type"`
	ActorID    uuid.UUID   `json:"actor_id"`
	ReceiptID  pgtype.UUID `json:"receipt_id"`
}

func (q *Queries) CreateInventoryEvent(ctx context.Context, arg CreateInventoryEventParams) (InventoryEvent, error) {
	row := q.db.QueryRow(ctx, createInventoryEvent,
		arg.ID,
		arg.BusinessID,
		arg.Type,
		arg.ActorID,
		arg.ReceiptID,
	)
	var i InventoryEvent
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Type,
		&i.ActorID,
		&i.ReceiptID,
		&i.OccurredAt,
		&i.CreatedAt,
	)
	return i, err
}

const createInventoryMovement = `-- name: CreateInventoryMovement :one
INSERT INTO inventory_movements (id, business_id, event_id, variant_id, location_id, quantity_delta)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, business_id, event_id, variant_id, location_id, quantity_delta, created_at
`

type CreateInventoryMovementParams struct {
	ID            uuid.UUID `json:"id"`
	BusinessID    uuid.UUID `json:"business_id"`
	EventID       uuid.UUID `json:"event_id"`
	VariantID     uuid.UUID `json:"variant_id"`
	LocationID    uuid.UUID `json:"location_id"`
	QuantityDelta int32     `json:"quantity_delta"`
}

func (q *Queries) CreateInventoryMovement(ctx context.Context, arg CreateInventoryMovementParams) (InventoryMovement, error) {
	row := q.db.QueryRow(ctx, createInventoryMovement,
		arg.ID,
		arg.BusinessID,
		arg.EventID,
		arg.VariantID,
		arg.LocationID,
		arg.QuantityDelta,
	)
	var i InventoryMovement
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.EventID,
		&i.VariantID,
		&i.LocationID,
		&i.QuantityDelta,
		&i.CreatedAt,
	)
	return i, err
}

const createStockLot = `-- name: CreateStockLot :one
INSERT INTO stock_lots (id, business_id, receipt_line_id, variant_id, location_id, received_quantity, total_cost_kobo, received_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, business_id, receipt_line_id, variant_id, location_id, received_quantity, total_cost_kobo, received_at, created_at
`

type CreateStockLotParams struct {
	ID               uuid.UUID          `json:"id"`
	BusinessID       uuid.UUID          `json:"business_id"`
	ReceiptLineID    uuid.UUID          `json:"receipt_line_id"`
	VariantID        uuid.UUID          `json:"variant_id"`
	LocationID       uuid.UUID          `json:"location_id"`
	ReceivedQuantity int32              `json:"received_quantity"`
	TotalCostKobo    int64              `json:"total_cost_kobo"`
	ReceivedAt       pgtype.Timestamptz `json:"received_at"`
}

func (q *Queries) CreateStockLot(ctx context.Context, arg CreateStockLotParams) (StockLot, error) {
	row := q.db.QueryRow(ctx, createStockLot,
		arg.ID,
		arg.BusinessID,
		arg.ReceiptLineID,
		arg.VariantID,
		arg.LocationID,
		arg.ReceivedQuantity,
		arg.TotalCostKobo,
		arg.ReceivedAt,
	)
	var i StockLot
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.ReceiptLineID,
		&i.VariantID,
		&i.LocationID,
		&i.ReceivedQuantity,
		&i.TotalCostKobo,
		&i.ReceivedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createStockReceipt = `-- name: CreateStockReceipt :one
INSERT INTO stock_receipts (id, business_id, location_id, received_by, received_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, business_id, location_id, received_by, received_at, created_at
`

type CreateStockReceiptParams struct {
	ID         uuid.UUID          `json:"id"`
	BusinessID uuid.UUID          `json:"business_id"`
	LocationID uuid.UUID          `json:"location_id"`
	ReceivedBy uuid.UUID          `json:"received_by"`
	ReceivedAt pgtype.Timestamptz `json:"received_at"`
}

func (q *Queries) CreateStockReceipt(ctx context.Context, arg CreateStockReceiptParams) (StockReceipt, error) {
	row := q.db.QueryRow(ctx, createStockReceipt,
		arg.ID,
		arg.BusinessID,
		arg.LocationID,
		arg.ReceivedBy,
		arg.ReceivedAt,
	)
	var i StockReceipt
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.LocationID,
		&i.ReceivedBy,
		&i.ReceivedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createStockReceiptLine = `-- name: CreateStockReceiptLine :one
INSERT INTO stock_receipt_lines (id, business_id, receipt_id, variant_id, quantity, total_cost_kobo)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, business_id, receipt_id, variant_id, quantity, total_cost_kobo, created_at
`

type CreateStockReceiptLineParams struct {
	ID            uuid.UUID `json:"id"`
	BusinessID    uuid.UUID `json:"business_id"`
	ReceiptID     uuid.UUID `json:"receipt_id"`
	VariantID     uuid.UUID `json:"variant_id"`
	Quantity      int32     `json:"quantity"`
	TotalCostKobo int64     `json:"total_cost_kobo"`
}

func (q *Queries) CreateStockReceiptLine(ctx context.Context, arg CreateStockReceiptLineParams) (StockReceiptLine, error) {
	row := q.db.QueryRow(ctx, createStockReceiptLine,
		arg.ID,
		arg.BusinessID,
		arg.ReceiptID,
		arg.VariantID,
		arg.Quantity,
		arg.TotalCostKobo,
	)
	var i StockReceiptLine
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.ReceiptID,
		&i.VariantID,
		&i.Quantity,
		&i.TotalCostKobo,
		&i.CreatedAt,
	)
	return i, err
}

const listInventoryBalances = `-- name: ListInventoryBalances :many
SELECT business_id, variant_id, location_id, quantity, updated_at FROM inventory_balances WHERE business_id = $1
`

func (q *Queries) ListInventoryBalances(ctx context.Context, businessID uuid.UUID) ([]InventoryBalance, error) {
	rows, err := q.db.Query(ctx, listInventoryBalances, businessID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InventoryBalance{}
	for rows.Next() {
		var i InventoryBalance
		if err := rows.Scan(
			&i.BusinessID,
			&i.VariantID,
			&i.LocationID,
			&i.Quantity,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertInventoryBalanceDelta = `-- name: UpsertInventoryBalanceDelta :one
INSERT INTO inventory_balances (business_id, variant_id, location_id, quantity, updated_at)
VALUES ($1, $2, $3, $4, now())
ON CONFLICT (business_id, variant_id, location_id) DO UPDATE
    SET quantity = inventory_balances.quantity + EXCLUDED.quantity, updated_at = now()
RETURNING business_id, variant_id, location_id, quantity, updated_at
`

type UpsertInventoryBalanceDeltaParams struct {
	BusinessID uuid.UUID `json:"business_id"`
	VariantID  uuid.UUID `json:"variant_id"`
	LocationID uuid.UUID `json:"location_id"`
	Quantity   int32     `json:"quantity"`
}

func (q *Queries) UpsertInventoryBalanceDelta(ctx context.Context, arg UpsertInventoryBalanceDeltaParams) (InventoryBalance, error) {
	row := q.db.QueryRow(ctx, upsertInventoryBalanceDelta,
		arg.BusinessID,
		arg.VariantID,
		arg.LocationID,
		arg.Quantity,
	)
	var i InventoryBalance
	err := row.Scan(
		&i.BusinessID,
		&i.VariantID,
		&i.LocationID,
		&i.Quantity,
		&i.UpdatedAt,
	)
	return i, err
}
