// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invitations.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const acceptInvitation = `-- name: AcceptInvitation :one
UPDATE invitations SET status = 'accepted', accepted_by = $2, accepted_at = now(), updated_at = now()
    WHERE id = $1 AND status = 'pending'
RETURNING id, business_id, invited_by, phone, email, role, token_hash, status, expires_at, accepted_by, accepted_at, created_at, updated_at
`

type AcceptInvitationParams struct {
	ID         uuid.UUID   `json:"id"`
	AcceptedBy pgtype.UUID `json:"accepted_by"`
}

func (q *Queries) AcceptInvitation(ctx context.Context, arg AcceptInvitationParams) (Invitation, error) {
	row := q.db.QueryRow(ctx, acceptInvitation, arg.ID, arg.AcceptedBy)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.InvitedBy,
		&i.Phone,
		&i.Email,
		&i.Role,
		&i.TokenHash,
		&i.Status,
		&i.ExpiresAt,
		&i.AcceptedBy,
		&i.AcceptedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createInvitation = `-- name: CreateInvitation :one
INSERT INTO invitations (id, business_id, invited_by, phone, email, role, token_hash, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, business_id, invited_by, phone, email, role, token_hash, status, expires_at, accepted_by, accepted_at, created_at, updated_at
`

type CreateInvitationParams struct {
	ID         uuid.UUID          `json:"id"`
	BusinessID uuid.UUID          `json:"business_id"`
	InvitedBy  uuid.UUID          `json:"invited_by"`
	Phone      pgtype.Text        `json:"phone"`
	Email      pgtype.Text        `json:"email"`
	Role       string             `json:"role"`
	TokenHash  string             `json:"token_hash"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateInvitation(ctx context.Context, arg CreateInvitationParams) (Invitation, error) {
	row := q.db.QueryRow(ctx, createInvitation,
		arg.ID,
		arg.BusinessID,
		arg.InvitedBy,
		arg.Phone,
		arg.Email,
		arg.Role,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.InvitedBy,
		&i.Phone,
		&i.Email,
		&i.Role,
		&i.TokenHash,
		&i.Status,
		&i.ExpiresAt,
		&i.AcceptedBy,
		&i.AcceptedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInvitationByID = `-- name: GetInvitationByID :one
SELECT id, business_id, invited_by, phone, email, role, token_hash, status, expires_at, accepted_by, accepted_at, created_at, updated_at FROM invitations WHERE business_id = $1 AND id = $2
`

type GetInvitationByIDParams struct {
	BusinessID uuid.UUID `json:"business_id"`
	ID         uuid.UUID `json:"id"`
}

func (q *Queries) GetInvitationByID(ctx context.Context, arg GetInvitationByIDParams) (Invitation, error) {
	row := q.db.QueryRow(ctx, getInvitationByID, arg.BusinessID, arg.ID)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.InvitedBy,
		&i.Phone,
		&i.Email,
		&i.Role,
		&i.TokenHash,
		&i.Status,
		&i.ExpiresAt,
		&i.AcceptedBy,
		&i.AcceptedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInvitationByTokenHash = `-- name: GetInvitationByTokenHash :one
SELECT id, business_id, invited_by, phone, email, role, token_hash, status, expires_at, accepted_by, accepted_at, created_at, updated_at FROM invitations WHERE token_hash = $1
`

// The public, unauthenticated lookup -- the hashed token is itself the
// access control (invitations carries no RLS; see migration 000021).
func (q *Queries) GetInvitationByTokenHash(ctx context.Context, tokenHash string) (Invitation, error) {
	row := q.db.QueryRow(ctx, getInvitationByTokenHash, tokenHash)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.InvitedBy,
		&i.Phone,
		&i.Email,
		&i.Role,
		&i.TokenHash,
		&i.Status,
		&i.ExpiresAt,
		&i.AcceptedBy,
		&i.AcceptedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listInvitationsByBusiness = `-- name: ListInvitationsByBusiness :many
SELECT id, business_id, invited_by, phone, email, role, token_hash, status, expires_at, accepted_by, accepted_at, created_at, updated_at FROM invitations WHERE business_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListInvitationsByBusiness(ctx context.Context, businessID uuid.UUID) ([]Invitation, error) {
	rows, err := q.db.Query(ctx, listInvitationsByBusiness, businessID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Invitation{}
	for rows.Next() {
		var i Invitation
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.InvitedBy,
			&i.Phone,
			&i.Email,
			&i.Role,
			&i.TokenHash,
			&i.Status,
			&i.ExpiresAt,
			&i.AcceptedBy,
			&i.AcceptedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeInvitation = `-- name: RevokeInvitation :one
UPDATE invitations SET status = 'revoked', updated_at = now()
    WHERE business_id = $1 AND id = $2 AND status = 'pending'
RETURNING id, business_id, invited_by, phone, email, role, token_hash, status, expires_at, accepted_by, accepted_at, created_at, updated_at
`

type RevokeInvitationParams struct {
	BusinessID uuid.UUID `json:"business_id"`
	ID         uuid.UUID `json:"id"`
}

func (q *Queries) RevokeInvitation(ctx context.Context, arg RevokeInvitationParams) (Invitation, error) {
	row := q.db.QueryRow(ctx, revokeInvitation, arg.BusinessID, arg.ID)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.InvitedBy,
		&i.Phone,
		&i.Email,
		&i.Role,
		&i.TokenHash,
		&i.Status,
		&i.ExpiresAt,
		&i.AcceptedBy,
		&i.AcceptedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
