// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: locations.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createDefaultLocation = `-- name: CreateDefaultLocation :one
INSERT INTO locations (id, business_id, name, is_default)
VALUES ($1, $2, 'Main', true)
RETURNING id, business_id, name, is_default, status, created_at, updated_at
`

type CreateDefaultLocationParams struct {
	ID         uuid.UUID `json:"id"`
	BusinessID uuid.UUID `json:"business_id"`
}

func (q *Queries) CreateDefaultLocation(ctx context.Context, arg CreateDefaultLocationParams) (Location, error) {
	row := q.db.QueryRow(ctx, createDefaultLocation, arg.ID, arg.BusinessID)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Name,
		&i.IsDefault,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDefaultLocation = `-- name: GetDefaultLocation :one
SELECT id, business_id, name, is_default, status, created_at, updated_at FROM locations WHERE business_id = $1 AND is_default = true
`

func (q *Queries) GetDefaultLocation(ctx context.Context, businessID uuid.UUID) (Location, error) {
	row := q.db.QueryRow(ctx, getDefaultLocation, businessID)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Name,
		&i.IsDefault,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLocationByID = `-- name: GetLocationByID :one
SELECT id, business_id, name, is_default, status, created_at, updated_at FROM locations WHERE business_id = $1 AND id = $2
`

type GetLocationByIDParams struct {
	BusinessID uuid.UUID `json:"business_id"`
	ID         uuid.UUID `json:"id"`
}

func (q *Queries) GetLocationByID(ctx context.Context, arg GetLocationByIDParams) (Location, error) {
	row := q.db.QueryRow(ctx, getLocationByID, arg.BusinessID, arg.ID)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Name,
		&i.IsDefault,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
