// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: memberships.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createMembership = `-- name: CreateMembership :one
INSERT INTO business_memberships (business_id, user_id, role, status, joined_at)
VALUES ($1, $2, $3, 'active', now())
RETURNING business_id, user_id, role, status, invited_at, joined_at, created_at, updated_at
`

type CreateMembershipParams struct {
	BusinessID uuid.UUID `json:"business_id"`
	UserID     uuid.UUID `json:"user_id"`
	Role       string    `json:"role"`
}

func (q *Queries) CreateMembership(ctx context.Context, arg CreateMembershipParams) (BusinessMembership, error) {
	row := q.db.QueryRow(ctx, createMembership, arg.BusinessID, arg.UserID, arg.Role)
	var i BusinessMembership
	err := row.Scan(
		&i.BusinessID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.InvitedAt,
		&i.JoinedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMembership = `-- name: GetMembership :one
SELECT business_id, user_id, role, status, invited_at, joined_at, created_at, updated_at FROM business_memberships
WHERE business_id = $1 AND user_id = $2
`

type GetMembershipParams struct {
	BusinessID uuid.UUID `json:"business_id"`
	UserID     uuid.UUID `json:"user_id"`
}

func (q *Queries) GetMembership(ctx context.Context, arg GetMembershipParams) (BusinessMembership, error) {
	row := q.db.QueryRow(ctx, getMembership, arg.BusinessID, arg.UserID)
	var i BusinessMembership
	err := row.Scan(
		&i.BusinessID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.InvitedAt,
		&i.JoinedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMembershipsForUser = `-- name: ListMembershipsForUser :many
SELECT bm.business_id, bm.user_id, bm.role, bm.status, bm.invited_at, bm.joined_at, bm.created_at, bm.updated_at, b.name AS business_name
FROM business_memberships bm
JOIN businesses b ON b.id = bm.business_id
WHERE bm.user_id = $1
ORDER BY bm.created_at
`

type ListMembershipsForUserRow struct {
	BusinessID   uuid.UUID          `json:"business_id"`
	UserID       uuid.UUID          `json:"user_id"`
	Role         string             `json:"role"`
	Status       string             `json:"status"`
	InvitedAt    pgtype.Timestamptz `json:"invited_at"`
	JoinedAt     pgtype.Timestamptz `json:"joined_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	BusinessName string             `json:"business_name"`
}

func (q *Queries) ListMembershipsForUser(ctx context.Context, userID uuid.UUID) ([]ListMembershipsForUserRow, error) {
	rows, err := q.db.Query(ctx, listMembershipsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMembershipsForUserRow{}
	for rows.Next() {
		var i ListMembershipsForUserRow
		if err := rows.Scan(
			&i.BusinessID,
			&i.UserID,
			&i.Role,
			&i.Status,
			&i.InvitedAt,
			&i.JoinedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BusinessName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
