// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Bill struct {
	ID          uuid.UUID          `json:"id"`
	BusinessID  uuid.UUID          `json:"business_id"`
	LocationID  uuid.UUID          `json:"location_id"`
	Status      string             `json:"status"`
	OpenedBy    uuid.UUID          `json:"opened_by"`
	OpenedAt    pgtype.Timestamptz `json:"opened_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	TableID     pgtype.UUID        `json:"table_id"`
	CustomerID  pgtype.UUID        `json:"customer_id"`
	BalanceKobo int64              `json:"balance_kobo"`
}

type BillShareLink struct {
	ID         uuid.UUID          `json:"id"`
	BusinessID uuid.UUID          `json:"business_id"`
	BillID     uuid.UUID          `json:"bill_id"`
	TokenHash  string             `json:"token_hash"`
	CreatedBy  uuid.UUID          `json:"created_by"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
}

type BillWriteOff struct {
	ID         uuid.UUID          `json:"id"`
	BusinessID uuid.UUID          `json:"business_id"`
	BillID     uuid.UUID          `json:"bill_id"`
	AmountKobo int64              `json:"amount_kobo"`
	Reason     string             `json:"reason"`
	ActorID    uuid.UUID          `json:"actor_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Business struct {
	ID                  uuid.UUID          `json:"id"`
	Name                string             `json:"name"`
	Timezone            string             `json:"timezone"`
	Currency            string             `json:"currency"`
	Phone               pgtype.Text        `json:"phone"`
	Address             pgtype.Text        `json:"address"`
	ReceiptWording      pgtype.Text        `json:"receipt_wording"`
	ReceiptFooter       pgtype.Text        `json:"receipt_footer"`
	PaymentInstructions pgtype.Text        `json:"payment_instructions"`
	LogoObjectKey       pgtype.Text        `json:"logo_object_key"`
	Status              string             `json:"status"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type BusinessMembership struct {
	BusinessID uuid.UUID          `json:"business_id"`
	UserID     uuid.UUID          `json:"user_id"`
	Role       string             `json:"role"`
	Status     string             `json:"status"`
	InvitedAt  pgtype.Timestamptz `json:"invited_at"`
	JoinedAt   pgtype.Timestamptz `json:"joined_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type CatalogueTemplate struct {
	ID           uuid.UUID          `json:"id"`
	Name         string             `json:"name"`
	CategoryName string             `json:"category_name"`
	SortOrder    int32              `json:"sort_order"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type CatalogueTemplateVariant struct {
	ID                 uuid.UUID          `json:"id"`
	TemplateID         uuid.UUID          `json:"template_id"`
	Name               string             `json:"name"`
	SuggestedPriceKobo int64              `json:"suggested_price_kobo"`
	SortOrder          int32              `json:"sort_order"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type Category struct {
	ID         uuid.UUID          `json:"id"`
	BusinessID uuid.UUID          `json:"business_id"`
	Name       string             `json:"name"`
	SortOrder  int32              `json:"sort_order"`
	Active     bool               `json:"active"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type Customer struct {
	ID         uuid.UUID          `json:"id"`
	BusinessID uuid.UUID          `json:"business_id"`
	Name       string             `json:"name"`
	Phone      pgtype.Text        `json:"phone"`
	Email      pgtype.Text        `json:"email"`
	Notes      pgtype.Text        `json:"notes"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type Device struct {
	ID          uuid.UUID          `json:"id"`
	BusinessID  uuid.UUID          `json:"business_id"`
	UserID      uuid.UUID          `json:"user_id"`
	LocationID  uuid.UUID          `json:"location_id"`
	PublicKey   string             `json:"public_key"`
	DisplayName string             `json:"display_name"`
	Status      string             `json:"status"`
	EnrolledAt  pgtype.Timestamptz `json:"enrolled_at"`
	LastSyncAt  pgtype.Timestamptz `json:"last_sync_at"`
	RevokedAt   pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Expense struct {
	ID                  uuid.UUID          `json:"id"`
	BusinessID          uuid.UUID          `json:"business_id"`
	LocationID          uuid.UUID          `json:"location_id"`
	CategoryID          uuid.UUID          `json:"category_id"`
	Description         string             `json:"description"`
	AmountKobo          int64              `json:"amount_kobo"`
	PaymentMethod       string             `json:"payment_method"`
	RecordedBy          uuid.UUID          `json:"recorded_by"`
	IdempotencyKey      uuid.UUID          `json:"idempotency_key"`
	OccurredAt          pgtype.Timestamptz `json:"occurred_at"`
	ReversalOfExpenseID pgtype.UUID        `json:"reversal_of_expense_id"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
}

type ExpenseCategory struct {
	ID         uuid.UUID          `json:"id"`
	BusinessID uuid.UUID          `json:"business_id"`
	Name       string             `json:"name"`
	Active     bool               `json:"active"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type IdentityVerification struct {
	ID         uuid.UUID          `json:"id"`
	UserID     uuid.UUID          `json:"user_id"`
	Channel    string             `json:"channel"`
	Identifier string             `json:"identifier"`
	OtpHash    string             `json:"otp_hash"`
	Purpose    string             `json:"purpose"`
	Attempts   int32              `json:"attempts"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type InventoryAdjustmentRequest struct {
	ID                uuid.UUID          `json:"id"`
	BusinessID        uuid.UUID          `json:"business_id"`
	LocationID        uuid.UUID          `json:"location_id"`
	VariantID         uuid.UUID          `json:"variant_id"`
	RequestedBy       uuid.UUID          `json:"requested_by"`
	IdempotencyKey    uuid.UUID          `json:"idempotency_key"`
	QuantityDelta     int32              `json:"quantity_delta"`
	ReasonCategory    string             `json:"reason_category"`
	ReasonNote        string             `json:"reason_note"`
	SourceCountLineID pgtype.UUID        `json:"source_count_line_id"`
	Status            string             `json:"status"`
	DecidedBy         pgtype.UUID        `json:"decided_by"`
	DecidedAt         pgtype.Timestamptz `json:"decided_at"`
	ResolutionNote    pgtype.Text        `json:"resolution_note"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type InventoryBalance struct {
	BusinessID uuid.UUID          `json:"business_id"`
	VariantID  uuid.UUID          `json:"variant_id"`
	LocationID uuid.UUID          `json:"location_id"`
	Quantity   int32              `json:"quantity"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type InventoryEvent struct {
	ID                  uuid.UUID          `json:"id"`
	BusinessID          uuid.UUID          `json:"business_id"`
	Type                string             `json:"type"`
	ActorID             uuid.UUID          `json:"actor_id"`
	ReceiptID           pgtype.UUID        `json:"receipt_id"`
	OccurredAt          pgtype.Timestamptz `json:"occurred_at"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	SaleID              pgtype.UUID        `json:"sale_id"`
	AdjustmentRequestID pgtype.UUID        `json:"adjustment_request_id"`
}

type InventoryMovement struct {
	ID            uuid.UUID          `json:"id"`
	BusinessID    uuid.UUID          `json:"business_id"`
	EventID       uuid.UUID          `json:"event_id"`
	VariantID     uuid.UUID          `json:"variant_id"`
	LocationID    uuid.UUID          `json:"location_id"`
	QuantityDelta int32              `json:"quantity_delta"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type InventoryReview struct {
	ID                 uuid.UUID          `json:"id"`
	BusinessID         uuid.UUID          `json:"business_id"`
	Type               string             `json:"type"`
	VariantID          uuid.UUID          `json:"variant_id"`
	LocationID         uuid.UUID          `json:"location_id"`
	RelatedMovementID  pgtype.UUID        `json:"related_movement_id"`
	RelatedCountLineID pgtype.UUID        `json:"related_count_line_id"`
	Status             string             `json:"status"`
	ResolvedBy         pgtype.UUID        `json:"resolved_by"`
	ResolvedNote       pgtype.Text        `json:"resolved_note"`
	ResolvedAt         pgtype.Timestamptz `json:"resolved_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type Invitation struct {
	ID         uuid.UUID          `json:"id"`
	BusinessID uuid.UUID          `json:"business_id"`
	InvitedBy  uuid.UUID          `json:"invited_by"`
	Phone      pgtype.Text        `json:"phone"`
	Email      pgtype.Text        `json:"email"`
	Role       string             `json:"role"`
	TokenHash  string             `json:"token_hash"`
	Status     string             `json:"status"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	AcceptedBy pgtype.UUID        `json:"accepted_by"`
	AcceptedAt pgtype.Timestamptz `json:"accepted_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type Location struct {
	ID         uuid.UUID          `json:"id"`
	BusinessID uuid.UUID          `json:"business_id"`
	Name       string             `json:"name"`
	IsDefault  bool               `json:"is_default"`
	Status     string             `json:"status"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type Payment struct {
	ID                  uuid.UUID          `json:"id"`
	BusinessID          uuid.UUID          `json:"business_id"`
	BillID              uuid.UUID          `json:"bill_id"`
	AmountKobo          int64              `json:"amount_kobo"`
	Method              string             `json:"method"`
	ActorID             uuid.UUID          `json:"actor_id"`
	ReversalOfPaymentID pgtype.UUID        `json:"reversal_of_payment_id"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
}

type PlatformAuditLog struct {
	ID               uuid.UUID          `json:"id"`
	PlatformStaffID  uuid.UUID          `json:"platform_staff_id"`
	Action           string             `json:"action"`
	TargetBusinessID pgtype.UUID        `json:"target_business_id"`
	Reason           pgtype.Text        `json:"reason"`
	RequestID        pgtype.Text        `json:"request_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type PlatformSession struct {
	ID            uuid.UUID          `json:"id"`
	StaffID       uuid.UUID          `json:"staff_id"`
	TokenHash     string             `json:"token_hash"`
	CsrfTokenHash string             `json:"csrf_token_hash"`
	UserAgent     pgtype.Text        `json:"user_agent"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	LastUsedAt    pgtype.Timestamptz `json:"last_used_at"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
	RevokedAt     pgtype.Timestamptz `json:"revoked_at"`
	RevokedReason pgtype.Text        `json:"revoked_reason"`
}

type PlatformStaff struct {
	ID           uuid.UUID          `json:"id"`
	Email        string             `json:"email"`
	DisplayName  string             `json:"display_name"`
	PasswordHash string             `json:"password_hash"`
	Role         string             `json:"role"`
	Status       string             `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Product struct {
	ID         uuid.UUID          `json:"id"`
	BusinessID uuid.UUID          `json:"business_id"`
	CategoryID pgtype.UUID        `json:"category_id"`
	Name       string             `json:"name"`
	Active     bool               `json:"active"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type ProductPrice struct {
	ID         uuid.UUID          `json:"id"`
	BusinessID uuid.UUID          `json:"business_id"`
	VariantID  uuid.UUID          `json:"variant_id"`
	AmountKobo int64              `json:"amount_kobo"`
	ValidFrom  pgtype.Timestamptz `json:"valid_from"`
	ValidTo    pgtype.Timestamptz `json:"valid_to"`
	CreatedBy  uuid.UUID          `json:"created_by"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type ProductVariant struct {
	ID              uuid.UUID          `json:"id"`
	BusinessID      uuid.UUID          `json:"business_id"`
	ProductID       uuid.UUID          `json:"product_id"`
	Name            string             `json:"name"`
	Active          bool               `json:"active"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	TracksInventory bool               `json:"tracks_inventory"`
}

type Sale struct {
	ID               uuid.UUID          `json:"id"`
	BusinessID       uuid.UUID          `json:"business_id"`
	BillID           uuid.UUID          `json:"bill_id"`
	SellerID         uuid.UUID          `json:"seller_id"`
	IdempotencyKey   uuid.UUID          `json:"idempotency_key"`
	OccurredAt       pgtype.Timestamptz `json:"occurred_at"`
	ReceivedAt       pgtype.Timestamptz `json:"received_at"`
	TotalKobo        int64              `json:"total_kobo"`
	ReversalOfSaleID pgtype.UUID        `json:"reversal_of_sale_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type SaleItem struct {
	ID            uuid.UUID          `json:"id"`
	BusinessID    uuid.UUID          `json:"business_id"`
	SaleID        uuid.UUID          `json:"sale_id"`
	VariantID     uuid.UUID          `json:"variant_id"`
	Description   string             `json:"description"`
	Quantity      int32              `json:"quantity"`
	UnitPriceKobo int64              `json:"unit_price_kobo"`
	LineTotalKobo int64              `json:"line_total_kobo"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type SaleReview struct {
	ID           uuid.UUID          `json:"id"`
	BusinessID   uuid.UUID          `json:"business_id"`
	SaleID       uuid.UUID          `json:"sale_id"`
	SaleItemID   pgtype.UUID        `json:"sale_item_id"`
	Reason       string             `json:"reason"`
	Status       string             `json:"status"`
	ResolvedBy   pgtype.UUID        `json:"resolved_by"`
	ResolvedNote pgtype.Text        `json:"resolved_note"`
	ResolvedAt   pgtype.Timestamptz `json:"resolved_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Session struct {
	ID            uuid.UUID          `json:"id"`
	UserID        uuid.UUID          `json:"user_id"`
	TokenHash     string             `json:"token_hash"`
	CsrfTokenHash string             `json:"csrf_token_hash"`
	UserAgent     pgtype.Text        `json:"user_agent"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	LastUsedAt    pgtype.Timestamptz `json:"last_used_at"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
	RevokedAt     pgtype.Timestamptz `json:"revoked_at"`
	RevokedReason pgtype.Text        `json:"revoked_reason"`
}

type SignupVerification struct {
	ID           uuid.UUID          `json:"id"`
	Email        pgtype.Text        `json:"email"`
	DisplayName  string             `json:"display_name"`
	PasswordHash string             `json:"password_hash"`
	OtpHash      string             `json:"otp_hash"`
	Attempts     int32              `json:"attempts"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	Phone        pgtype.Text        `json:"phone"`
	Channel      string             `json:"channel"`
}

type StockCount struct {
	ID             uuid.UUID          `json:"id"`
	BusinessID     uuid.UUID          `json:"business_id"`
	LocationID     uuid.UUID          `json:"location_id"`
	CountedBy      uuid.UUID          `json:"counted_by"`
	IdempotencyKey uuid.UUID          `json:"idempotency_key"`
	StartedAt      pgtype.Timestamptz `json:"started_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type StockCountLine struct {
	ID               uuid.UUID          `json:"id"`
	BusinessID       uuid.UUID          `json:"business_id"`
	CountID          uuid.UUID          `json:"count_id"`
	VariantID        uuid.UUID          `json:"variant_id"`
	ExpectedQuantity int32              `json:"expected_quantity"`
	PhysicalQuantity int32              `json:"physical_quantity"`
	Variance         int32              `json:"variance"`
	IsStale          bool               `json:"is_stale"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type StockLot struct {
	ID               uuid.UUID          `json:"id"`
	BusinessID       uuid.UUID          `json:"business_id"`
	ReceiptLineID    uuid.UUID          `json:"receipt_line_id"`
	VariantID        uuid.UUID          `json:"variant_id"`
	LocationID       uuid.UUID          `json:"location_id"`
	ReceivedQuantity int32              `json:"received_quantity"`
	TotalCostKobo    int64              `json:"total_cost_kobo"`
	ReceivedAt       pgtype.Timestamptz `json:"received_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type StockReceipt struct {
	ID         uuid.UUID          `json:"id"`
	BusinessID uuid.UUID          `json:"business_id"`
	LocationID uuid.UUID          `json:"location_id"`
	ReceivedBy uuid.UUID          `json:"received_by"`
	ReceivedAt pgtype.Timestamptz `json:"received_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type StockReceiptLine struct {
	ID            uuid.UUID          `json:"id"`
	BusinessID    uuid.UUID          `json:"business_id"`
	ReceiptID     uuid.UUID          `json:"receipt_id"`
	VariantID     uuid.UUID          `json:"variant_id"`
	Quantity      int32              `json:"quantity"`
	TotalCostKobo int64              `json:"total_cost_kobo"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type Table struct {
	ID         uuid.UUID          `json:"id"`
	BusinessID uuid.UUID          `json:"business_id"`
	Label      string             `json:"label"`
	Active     bool               `json:"active"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           uuid.UUID          `json:"id"`
	Email        pgtype.Text        `json:"email"`
	Phone        pgtype.Text        `json:"phone"`
	DisplayName  string             `json:"display_name"`
	PasswordHash pgtype.Text        `json:"password_hash"`
	Status       string             `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type UserIdentity struct {
	ID             uuid.UUID          `json:"id"`
	UserID         uuid.UUID          `json:"user_id"`
	Provider       string             `json:"provider"`
	ProviderUserID string             `json:"provider_user_id"`
	Email          string             `json:"email"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}
