// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Business struct {
	ID                  uuid.UUID          `json:"id"`
	Name                string             `json:"name"`
	Timezone            string             `json:"timezone"`
	Currency            string             `json:"currency"`
	Phone               pgtype.Text        `json:"phone"`
	Address             pgtype.Text        `json:"address"`
	ReceiptWording      pgtype.Text        `json:"receipt_wording"`
	ReceiptFooter       pgtype.Text        `json:"receipt_footer"`
	PaymentInstructions pgtype.Text        `json:"payment_instructions"`
	LogoObjectKey       pgtype.Text        `json:"logo_object_key"`
	Status              string             `json:"status"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type BusinessMembership struct {
	BusinessID uuid.UUID          `json:"business_id"`
	UserID     uuid.UUID          `json:"user_id"`
	Role       string             `json:"role"`
	Status     string             `json:"status"`
	InvitedAt  pgtype.Timestamptz `json:"invited_at"`
	JoinedAt   pgtype.Timestamptz `json:"joined_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type CatalogueTemplate struct {
	ID           uuid.UUID          `json:"id"`
	Name         string             `json:"name"`
	CategoryName string             `json:"category_name"`
	SortOrder    int32              `json:"sort_order"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type CatalogueTemplateVariant struct {
	ID                 uuid.UUID          `json:"id"`
	TemplateID         uuid.UUID          `json:"template_id"`
	Name               string             `json:"name"`
	SuggestedPriceKobo int64              `json:"suggested_price_kobo"`
	SortOrder          int32              `json:"sort_order"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type Category struct {
	ID         uuid.UUID          `json:"id"`
	BusinessID uuid.UUID          `json:"business_id"`
	Name       string             `json:"name"`
	SortOrder  int32              `json:"sort_order"`
	Active     bool               `json:"active"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type Device struct {
	ID          uuid.UUID          `json:"id"`
	BusinessID  uuid.UUID          `json:"business_id"`
	UserID      uuid.UUID          `json:"user_id"`
	LocationID  uuid.UUID          `json:"location_id"`
	PublicKey   string             `json:"public_key"`
	DisplayName string             `json:"display_name"`
	Status      string             `json:"status"`
	EnrolledAt  pgtype.Timestamptz `json:"enrolled_at"`
	LastSyncAt  pgtype.Timestamptz `json:"last_sync_at"`
	RevokedAt   pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Location struct {
	ID         uuid.UUID          `json:"id"`
	BusinessID uuid.UUID          `json:"business_id"`
	Name       string             `json:"name"`
	IsDefault  bool               `json:"is_default"`
	Status     string             `json:"status"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type Product struct {
	ID         uuid.UUID          `json:"id"`
	BusinessID uuid.UUID          `json:"business_id"`
	CategoryID pgtype.UUID        `json:"category_id"`
	Name       string             `json:"name"`
	Active     bool               `json:"active"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type ProductPrice struct {
	ID         uuid.UUID          `json:"id"`
	BusinessID uuid.UUID          `json:"business_id"`
	VariantID  uuid.UUID          `json:"variant_id"`
	AmountKobo int64              `json:"amount_kobo"`
	ValidFrom  pgtype.Timestamptz `json:"valid_from"`
	ValidTo    pgtype.Timestamptz `json:"valid_to"`
	CreatedBy  uuid.UUID          `json:"created_by"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type ProductVariant struct {
	ID         uuid.UUID          `json:"id"`
	BusinessID uuid.UUID          `json:"business_id"`
	ProductID  uuid.UUID          `json:"product_id"`
	Name       string             `json:"name"`
	Active     bool               `json:"active"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type Session struct {
	ID            uuid.UUID          `json:"id"`
	UserID        uuid.UUID          `json:"user_id"`
	TokenHash     string             `json:"token_hash"`
	CsrfTokenHash string             `json:"csrf_token_hash"`
	UserAgent     pgtype.Text        `json:"user_agent"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	LastUsedAt    pgtype.Timestamptz `json:"last_used_at"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
	RevokedAt     pgtype.Timestamptz `json:"revoked_at"`
	RevokedReason pgtype.Text        `json:"revoked_reason"`
}

type User struct {
	ID           uuid.UUID          `json:"id"`
	Email        string             `json:"email"`
	Phone        pgtype.Text        `json:"phone"`
	DisplayName  string             `json:"display_name"`
	PasswordHash string             `json:"password_hash"`
	Status       string             `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
