// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: platform_sessions.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createPlatformSession = `-- name: CreatePlatformSession :one
INSERT INTO platform_sessions (id, staff_id, token_hash, csrf_token_hash, user_agent, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, staff_id, token_hash, csrf_token_hash, user_agent, created_at, last_used_at, expires_at, revoked_at, revoked_reason
`

type CreatePlatformSessionParams struct {
	ID            uuid.UUID          `json:"id"`
	StaffID       uuid.UUID          `json:"staff_id"`
	TokenHash     string             `json:"token_hash"`
	CsrfTokenHash string             `json:"csrf_token_hash"`
	UserAgent     pgtype.Text        `json:"user_agent"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreatePlatformSession(ctx context.Context, arg CreatePlatformSessionParams) (PlatformSession, error) {
	row := q.db.QueryRow(ctx, createPlatformSession,
		arg.ID,
		arg.StaffID,
		arg.TokenHash,
		arg.CsrfTokenHash,
		arg.UserAgent,
		arg.ExpiresAt,
	)
	var i PlatformSession
	err := row.Scan(
		&i.ID,
		&i.StaffID,
		&i.TokenHash,
		&i.CsrfTokenHash,
		&i.UserAgent,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RevokedReason,
	)
	return i, err
}

const getActivePlatformSessionByTokenHash = `-- name: GetActivePlatformSessionByTokenHash :one
SELECT id, staff_id, token_hash, csrf_token_hash, user_agent, created_at, last_used_at, expires_at, revoked_at, revoked_reason FROM platform_sessions
WHERE token_hash = $1 AND revoked_at IS NULL AND expires_at > now()
`

func (q *Queries) GetActivePlatformSessionByTokenHash(ctx context.Context, tokenHash string) (PlatformSession, error) {
	row := q.db.QueryRow(ctx, getActivePlatformSessionByTokenHash, tokenHash)
	var i PlatformSession
	err := row.Scan(
		&i.ID,
		&i.StaffID,
		&i.TokenHash,
		&i.CsrfTokenHash,
		&i.UserAgent,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RevokedReason,
	)
	return i, err
}

const revokePlatformSession = `-- name: RevokePlatformSession :execrows
UPDATE platform_sessions
SET revoked_at = now(), revoked_reason = $2
WHERE id = $1 AND staff_id = $3 AND revoked_at IS NULL
`

type RevokePlatformSessionParams struct {
	ID            uuid.UUID   `json:"id"`
	RevokedReason pgtype.Text `json:"revoked_reason"`
	StaffID       uuid.UUID   `json:"staff_id"`
}

func (q *Queries) RevokePlatformSession(ctx context.Context, arg RevokePlatformSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokePlatformSession, arg.ID, arg.RevokedReason, arg.StaffID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchPlatformSession = `-- name: TouchPlatformSession :exec
UPDATE platform_sessions SET last_used_at = now() WHERE id = $1
`

func (q *Queries) TouchPlatformSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchPlatformSession, id)
	return err
}
