// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: platform_staff.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createPlatformStaff = `-- name: CreatePlatformStaff :one
INSERT INTO platform_staff (id, email, display_name, password_hash, role)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, email, display_name, password_hash, role, status, created_at, updated_at
`

type CreatePlatformStaffParams struct {
	ID           uuid.UUID `json:"id"`
	Email        string    `json:"email"`
	DisplayName  string    `json:"display_name"`
	PasswordHash string    `json:"password_hash"`
	Role         string    `json:"role"`
}

func (q *Queries) CreatePlatformStaff(ctx context.Context, arg CreatePlatformStaffParams) (PlatformStaff, error) {
	row := q.db.QueryRow(ctx, createPlatformStaff,
		arg.ID,
		arg.Email,
		arg.DisplayName,
		arg.PasswordHash,
		arg.Role,
	)
	var i PlatformStaff
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlatformStaffByEmail = `-- name: GetPlatformStaffByEmail :one
SELECT id, email, display_name, password_hash, role, status, created_at, updated_at FROM platform_staff WHERE lower(email) = lower($1)
`

func (q *Queries) GetPlatformStaffByEmail(ctx context.Context, email string) (PlatformStaff, error) {
	row := q.db.QueryRow(ctx, getPlatformStaffByEmail, email)
	var i PlatformStaff
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlatformStaffByID = `-- name: GetPlatformStaffByID :one
SELECT id, email, display_name, password_hash, role, status, created_at, updated_at FROM platform_staff WHERE id = $1
`

func (q *Queries) GetPlatformStaffByID(ctx context.Context, id uuid.UUID) (PlatformStaff, error) {
	row := q.db.QueryRow(ctx, getPlatformStaffByID, id)
	var i PlatformStaff
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPlatformStaff = `-- name: ListPlatformStaff :many
SELECT id, email, display_name, password_hash, role, status, created_at, updated_at FROM platform_staff ORDER BY created_at
`

func (q *Queries) ListPlatformStaff(ctx context.Context) ([]PlatformStaff, error) {
	rows, err := q.db.Query(ctx, listPlatformStaff)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlatformStaff{}
	for rows.Next() {
		var i PlatformStaff
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.DisplayName,
			&i.PasswordHash,
			&i.Role,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPlatformStaffStatus = `-- name: SetPlatformStaffStatus :one
UPDATE platform_staff SET status = $2, updated_at = now() WHERE id = $1 RETURNING id, email, display_name, password_hash, role, status, created_at, updated_at
`

type SetPlatformStaffStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) SetPlatformStaffStatus(ctx context.Context, arg SetPlatformStaffStatusParams) (PlatformStaff, error) {
	row := q.db.QueryRow(ctx, setPlatformStaffStatus, arg.ID, arg.Status)
	var i PlatformStaff
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
