// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: platform_businesses.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const countUsers = `-- name: CountUsers :one
SELECT count(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listAllBusinesses = `-- name: ListAllBusinesses :many
SELECT id, name, timezone, currency, phone, address, receipt_wording, receipt_footer, payment_instructions, logo_object_key, status, created_at, updated_at FROM businesses ORDER BY created_at DESC
`

func (q *Queries) ListAllBusinesses(ctx context.Context) ([]Business, error) {
	rows, err := q.db.Query(ctx, listAllBusinesses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Business{}
	for rows.Next() {
		var i Business
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Timezone,
			&i.Currency,
			&i.Phone,
			&i.Address,
			&i.ReceiptWording,
			&i.ReceiptFooter,
			&i.PaymentInstructions,
			&i.LogoObjectKey,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setBusinessStatus = `-- name: SetBusinessStatus :one
UPDATE businesses SET status = $2, updated_at = now() WHERE id = $1 RETURNING id, name, timezone, currency, phone, address, receipt_wording, receipt_footer, payment_instructions, logo_object_key, status, created_at, updated_at
`

type SetBusinessStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) SetBusinessStatus(ctx context.Context, arg SetBusinessStatusParams) (Business, error) {
	row := q.db.QueryRow(ctx, setBusinessStatus, arg.ID, arg.Status)
	var i Business
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Timezone,
		&i.Currency,
		&i.Phone,
		&i.Address,
		&i.ReceiptWording,
		&i.ReceiptFooter,
		&i.PaymentInstructions,
		&i.LogoObjectKey,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
