// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: platform_staff.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createPlatformStaff = `-- name: CreatePlatformStaff :one
INSERT INTO platform_staff (id, email, display_name, password_hash, role)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, email, display_name, password_hash, role, status, created_at, updated_at
`

type CreatePlatformStaffParams struct {
	ID           uuid.UUID `json:"id"`
	Email        string    `json:"email"`
	DisplayName  string    `json:"display_name"`
	PasswordHash string    `json:"password_hash"`
	Role         string    `json:"role"`
}

func (q *Queries) CreatePlatformStaff(ctx context.Context, arg CreatePlatformStaffParams) (PlatformStaff, error) {
	row := q.db.QueryRow(ctx, createPlatformStaff,
		arg.ID,
		arg.Email,
		arg.DisplayName,
		arg.PasswordHash,
		arg.Role,
	)
	var i PlatformStaff
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlatformStaffByEmail = `-- name: GetPlatformStaffByEmail :one
SELECT id, email, display_name, password_hash, role, status, created_at, updated_at FROM platform_staff WHERE lower(email) = lower($1)
`

func (q *Queries) GetPlatformStaffByEmail(ctx context.Context, email string) (PlatformStaff, error) {
	row := q.db.QueryRow(ctx, getPlatformStaffByEmail, email)
	var i PlatformStaff
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlatformStaffByID = `-- name: GetPlatformStaffByID :one
SELECT id, email, display_name, password_hash, role, status, created_at, updated_at FROM platform_staff WHERE id = $1
`

func (q *Queries) GetPlatformStaffByID(ctx context.Context, id uuid.UUID) (PlatformStaff, error) {
	row := q.db.QueryRow(ctx, getPlatformStaffByID, id)
	var i PlatformStaff
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
