// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: platform_audit_log.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createPlatformAuditEntry = `-- name: CreatePlatformAuditEntry :one
INSERT INTO platform_audit_log (id, platform_staff_id, action, target_business_id, target_staff_id, reason, request_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, platform_staff_id, action, target_business_id, reason, request_id, created_at, target_staff_id
`

type CreatePlatformAuditEntryParams struct {
	ID               uuid.UUID   `json:"id"`
	PlatformStaffID  uuid.UUID   `json:"platform_staff_id"`
	Action           string      `json:"action"`
	TargetBusinessID pgtype.UUID `json:"target_business_id"`
	TargetStaffID    pgtype.UUID `json:"target_staff_id"`
	Reason           pgtype.Text `json:"reason"`
	RequestID        pgtype.Text `json:"request_id"`
}

func (q *Queries) CreatePlatformAuditEntry(ctx context.Context, arg CreatePlatformAuditEntryParams) (PlatformAuditLog, error) {
	row := q.db.QueryRow(ctx, createPlatformAuditEntry,
		arg.ID,
		arg.PlatformStaffID,
		arg.Action,
		arg.TargetBusinessID,
		arg.TargetStaffID,
		arg.Reason,
		arg.RequestID,
	)
	var i PlatformAuditLog
	err := row.Scan(
		&i.ID,
		&i.PlatformStaffID,
		&i.Action,
		&i.TargetBusinessID,
		&i.Reason,
		&i.RequestID,
		&i.CreatedAt,
		&i.TargetStaffID,
	)
	return i, err
}

const listPlatformAuditLog = `-- name: ListPlatformAuditLog :many
SELECT id, platform_staff_id, action, target_business_id, reason, request_id, created_at, target_staff_id FROM platform_audit_log ORDER BY created_at DESC LIMIT $1
`

func (q *Queries) ListPlatformAuditLog(ctx context.Context, limit int32) ([]PlatformAuditLog, error) {
	rows, err := q.db.Query(ctx, listPlatformAuditLog, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlatformAuditLog{}
	for rows.Next() {
		var i PlatformAuditLog
		if err := rows.Scan(
			&i.ID,
			&i.PlatformStaffID,
			&i.Action,
			&i.TargetBusinessID,
			&i.Reason,
			&i.RequestID,
			&i.CreatedAt,
			&i.TargetStaffID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
