// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: product_variant_price_packs.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const closeCurrentPricePacksForVariant = `-- name: CloseCurrentPricePacksForVariant :exec
UPDATE product_variant_price_packs
SET valid_to = $3
WHERE business_id = $1 AND variant_id = $2 AND valid_to IS NULL
`

type CloseCurrentPricePacksForVariantParams struct {
	BusinessID uuid.UUID          `json:"business_id"`
	VariantID  uuid.UUID          `json:"variant_id"`
	ValidTo    pgtype.Timestamptz `json:"valid_to"`
}

func (q *Queries) CloseCurrentPricePacksForVariant(ctx context.Context, arg CloseCurrentPricePacksForVariantParams) error {
	_, err := q.db.Exec(ctx, closeCurrentPricePacksForVariant, arg.BusinessID, arg.VariantID, arg.ValidTo)
	return err
}

const createPricePack = `-- name: CreatePricePack :one
INSERT INTO product_variant_price_packs (id, business_id, variant_id, pack_quantity, pack_price_kobo, valid_from, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, business_id, variant_id, pack_quantity, pack_price_kobo, valid_from, valid_to, created_by, created_at
`

type CreatePricePackParams struct {
	ID            uuid.UUID          `json:"id"`
	BusinessID    uuid.UUID          `json:"business_id"`
	VariantID     uuid.UUID          `json:"variant_id"`
	PackQuantity  int32              `json:"pack_quantity"`
	PackPriceKobo int64              `json:"pack_price_kobo"`
	ValidFrom     pgtype.Timestamptz `json:"valid_from"`
	CreatedBy     uuid.UUID          `json:"created_by"`
}

func (q *Queries) CreatePricePack(ctx context.Context, arg CreatePricePackParams) (ProductVariantPricePack, error) {
	row := q.db.QueryRow(ctx, createPricePack,
		arg.ID,
		arg.BusinessID,
		arg.VariantID,
		arg.PackQuantity,
		arg.PackPriceKobo,
		arg.ValidFrom,
		arg.CreatedBy,
	)
	var i ProductVariantPricePack
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.VariantID,
		&i.PackQuantity,
		&i.PackPriceKobo,
		&i.ValidFrom,
		&i.ValidTo,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listCurrentPricePacksByBusiness = `-- name: ListCurrentPricePacksByBusiness :many
SELECT id, business_id, variant_id, pack_quantity, pack_price_kobo, valid_from, valid_to, created_by, created_at FROM product_variant_price_packs
    WHERE business_id = $1 AND valid_to IS NULL
    ORDER BY variant_id, pack_quantity
`

// Backs Service.ListCatalogue's one-query-per-business composition, the
// same shape ListCurrentPricesByBusiness already uses for the flat prices
// themselves.
func (q *Queries) ListCurrentPricePacksByBusiness(ctx context.Context, businessID uuid.UUID) ([]ProductVariantPricePack, error) {
	rows, err := q.db.Query(ctx, listCurrentPricePacksByBusiness, businessID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProductVariantPricePack{}
	for rows.Next() {
		var i ProductVariantPricePack
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.VariantID,
			&i.PackQuantity,
			&i.PackPriceKobo,
			&i.ValidFrom,
			&i.ValidTo,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCurrentPricePacksByVariant = `-- name: ListCurrentPricePacksByVariant :many
SELECT id, business_id, variant_id, pack_quantity, pack_price_kobo, valid_from, valid_to, created_by, created_at FROM product_variant_price_packs
    WHERE business_id = $1 AND variant_id = $2 AND valid_to IS NULL
    ORDER BY pack_quantity
`

type ListCurrentPricePacksByVariantParams struct {
	BusinessID uuid.UUID `json:"business_id"`
	VariantID  uuid.UUID `json:"variant_id"`
}

func (q *Queries) ListCurrentPricePacksByVariant(ctx context.Context, arg ListCurrentPricePacksByVariantParams) ([]ProductVariantPricePack, error) {
	rows, err := q.db.Query(ctx, listCurrentPricePacksByVariant, arg.BusinessID, arg.VariantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProductVariantPricePack{}
	for rows.Next() {
		var i ProductVariantPricePack
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.VariantID,
			&i.PackQuantity,
			&i.PackPriceKobo,
			&i.ValidFrom,
			&i.ValidTo,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
