// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: product_prices.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const closeCurrentPrice = `-- name: CloseCurrentPrice :exec
UPDATE product_prices
SET valid_to = $3
WHERE business_id = $1 AND variant_id = $2 AND valid_to IS NULL
`

type CloseCurrentPriceParams struct {
	BusinessID uuid.UUID          `json:"business_id"`
	VariantID  uuid.UUID          `json:"variant_id"`
	ValidTo    pgtype.Timestamptz `json:"valid_to"`
}

func (q *Queries) CloseCurrentPrice(ctx context.Context, arg CloseCurrentPriceParams) error {
	_, err := q.db.Exec(ctx, closeCurrentPrice, arg.BusinessID, arg.VariantID, arg.ValidTo)
	return err
}

const createPrice = `-- name: CreatePrice :one
INSERT INTO product_prices (id, business_id, variant_id, amount_kobo, valid_from, created_by)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, business_id, variant_id, amount_kobo, valid_from, valid_to, created_by, created_at
`

type CreatePriceParams struct {
	ID         uuid.UUID          `json:"id"`
	BusinessID uuid.UUID          `json:"business_id"`
	VariantID  uuid.UUID          `json:"variant_id"`
	AmountKobo int64              `json:"amount_kobo"`
	ValidFrom  pgtype.Timestamptz `json:"valid_from"`
	CreatedBy  uuid.UUID          `json:"created_by"`
}

func (q *Queries) CreatePrice(ctx context.Context, arg CreatePriceParams) (ProductPrice, error) {
	row := q.db.QueryRow(ctx, createPrice,
		arg.ID,
		arg.BusinessID,
		arg.VariantID,
		arg.AmountKobo,
		arg.ValidFrom,
		arg.CreatedBy,
	)
	var i ProductPrice
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.VariantID,
		&i.AmountKobo,
		&i.ValidFrom,
		&i.ValidTo,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getCurrentPrice = `-- name: GetCurrentPrice :one
SELECT id, business_id, variant_id, amount_kobo, valid_from, valid_to, created_by, created_at FROM product_prices WHERE business_id = $1 AND variant_id = $2 AND valid_to IS NULL
`

type GetCurrentPriceParams struct {
	BusinessID uuid.UUID `json:"business_id"`
	VariantID  uuid.UUID `json:"variant_id"`
}

func (q *Queries) GetCurrentPrice(ctx context.Context, arg GetCurrentPriceParams) (ProductPrice, error) {
	row := q.db.QueryRow(ctx, getCurrentPrice, arg.BusinessID, arg.VariantID)
	var i ProductPrice
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.VariantID,
		&i.AmountKobo,
		&i.ValidFrom,
		&i.ValidTo,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getPriceAt = `-- name: GetPriceAt :one
SELECT id, business_id, variant_id, amount_kobo, valid_from, valid_to, created_by, created_at FROM product_prices
    WHERE business_id = $1 AND variant_id = $2 AND valid_from <= $3 AND (valid_to IS NULL OR valid_to > $3)
    LIMIT 1
`

type GetPriceAtParams struct {
	BusinessID uuid.UUID          `json:"business_id"`
	VariantID  uuid.UUID          `json:"variant_id"`
	ValidFrom  pgtype.Timestamptz `json:"valid_from"`
}

func (q *Queries) GetPriceAt(ctx context.Context, arg GetPriceAtParams) (ProductPrice, error) {
	row := q.db.QueryRow(ctx, getPriceAt, arg.BusinessID, arg.VariantID, arg.ValidFrom)
	var i ProductPrice
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.VariantID,
		&i.AmountKobo,
		&i.ValidFrom,
		&i.ValidTo,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listCurrentPricesByBusiness = `-- name: ListCurrentPricesByBusiness :many
SELECT id, business_id, variant_id, amount_kobo, valid_from, valid_to, created_by, created_at FROM product_prices WHERE business_id = $1 AND valid_to IS NULL
`

func (q *Queries) ListCurrentPricesByBusiness(ctx context.Context, businessID uuid.UUID) ([]ProductPrice, error) {
	rows, err := q.db.Query(ctx, listCurrentPricesByBusiness, businessID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProductPrice{}
	for rows.Next() {
		var i ProductPrice
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.VariantID,
			&i.AmountKobo,
			&i.ValidFrom,
			&i.ValidTo,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPriceHistory = `-- name: ListPriceHistory :many
SELECT id, business_id, variant_id, amount_kobo, valid_from, valid_to, created_by, created_at FROM product_prices WHERE business_id = $1 AND variant_id = $2 ORDER BY valid_from DESC
`

type ListPriceHistoryParams struct {
	BusinessID uuid.UUID `json:"business_id"`
	VariantID  uuid.UUID `json:"variant_id"`
}

func (q *Queries) ListPriceHistory(ctx context.Context, arg ListPriceHistoryParams) ([]ProductPrice, error) {
	rows, err := q.db.Query(ctx, listPriceHistory, arg.BusinessID, arg.VariantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProductPrice{}
	for rows.Next() {
		var i ProductPrice
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.VariantID,
			&i.AmountKobo,
			&i.ValidFrom,
			&i.ValidTo,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
