// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: product_variants.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createVariant = `-- name: CreateVariant :one
INSERT INTO product_variants (id, business_id, product_id, name)
VALUES ($1, $2, $3, $4)
RETURNING id, business_id, product_id, name, active, created_at, updated_at
`

type CreateVariantParams struct {
	ID         uuid.UUID `json:"id"`
	BusinessID uuid.UUID `json:"business_id"`
	ProductID  uuid.UUID `json:"product_id"`
	Name       string    `json:"name"`
}

func (q *Queries) CreateVariant(ctx context.Context, arg CreateVariantParams) (ProductVariant, error) {
	row := q.db.QueryRow(ctx, createVariant,
		arg.ID,
		arg.BusinessID,
		arg.ProductID,
		arg.Name,
	)
	var i ProductVariant
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.ProductID,
		&i.Name,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVariantByID = `-- name: GetVariantByID :one
SELECT id, business_id, product_id, name, active, created_at, updated_at FROM product_variants WHERE business_id = $1 AND id = $2
`

type GetVariantByIDParams struct {
	BusinessID uuid.UUID `json:"business_id"`
	ID         uuid.UUID `json:"id"`
}

func (q *Queries) GetVariantByID(ctx context.Context, arg GetVariantByIDParams) (ProductVariant, error) {
	row := q.db.QueryRow(ctx, getVariantByID, arg.BusinessID, arg.ID)
	var i ProductVariant
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.ProductID,
		&i.Name,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listVariantsByBusiness = `-- name: ListVariantsByBusiness :many
SELECT id, business_id, product_id, name, active, created_at, updated_at FROM product_variants WHERE business_id = $1 ORDER BY product_id, name
`

func (q *Queries) ListVariantsByBusiness(ctx context.Context, businessID uuid.UUID) ([]ProductVariant, error) {
	rows, err := q.db.Query(ctx, listVariantsByBusiness, businessID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProductVariant{}
	for rows.Next() {
		var i ProductVariant
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.ProductID,
			&i.Name,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVariantsByProduct = `-- name: ListVariantsByProduct :many
SELECT id, business_id, product_id, name, active, created_at, updated_at FROM product_variants WHERE business_id = $1 AND product_id = $2 ORDER BY name
`

type ListVariantsByProductParams struct {
	BusinessID uuid.UUID `json:"business_id"`
	ProductID  uuid.UUID `json:"product_id"`
}

func (q *Queries) ListVariantsByProduct(ctx context.Context, arg ListVariantsByProductParams) ([]ProductVariant, error) {
	rows, err := q.db.Query(ctx, listVariantsByProduct, arg.BusinessID, arg.ProductID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProductVariant{}
	for rows.Next() {
		var i ProductVariant
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.ProductID,
			&i.Name,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVariant = `-- name: UpdateVariant :one
UPDATE product_variants
SET name = $3, active = $4, updated_at = now()
WHERE business_id = $1 AND id = $2
RETURNING id, business_id, product_id, name, active, created_at, updated_at
`

type UpdateVariantParams struct {
	BusinessID uuid.UUID `json:"business_id"`
	ID         uuid.UUID `json:"id"`
	Name       string    `json:"name"`
	Active     bool      `json:"active"`
}

func (q *Queries) UpdateVariant(ctx context.Context, arg UpdateVariantParams) (ProductVariant, error) {
	row := q.db.QueryRow(ctx, updateVariant,
		arg.BusinessID,
		arg.ID,
		arg.Name,
		arg.Active,
	)
	var i ProductVariant
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.ProductID,
		&i.Name,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
