// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: products.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (id, business_id, category_id, name)
VALUES ($1, $2, $3, $4)
RETURNING id, business_id, category_id, name, active, created_at, updated_at
`

type CreateProductParams struct {
	ID         uuid.UUID   `json:"id"`
	BusinessID uuid.UUID   `json:"business_id"`
	CategoryID pgtype.UUID `json:"category_id"`
	Name       string      `json:"name"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.ID,
		arg.BusinessID,
		arg.CategoryID,
		arg.Name,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.CategoryID,
		&i.Name,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProductByID = `-- name: GetProductByID :one
SELECT id, business_id, category_id, name, active, created_at, updated_at FROM products WHERE business_id = $1 AND id = $2
`

type GetProductByIDParams struct {
	BusinessID uuid.UUID `json:"business_id"`
	ID         uuid.UUID `json:"id"`
}

func (q *Queries) GetProductByID(ctx context.Context, arg GetProductByIDParams) (Product, error) {
	row := q.db.QueryRow(ctx, getProductByID, arg.BusinessID, arg.ID)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.CategoryID,
		&i.Name,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProducts = `-- name: ListProducts :many
SELECT id, business_id, category_id, name, active, created_at, updated_at FROM products WHERE business_id = $1 ORDER BY name
`

func (q *Queries) ListProducts(ctx context.Context, businessID uuid.UUID) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProducts, businessID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.CategoryID,
			&i.Name,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products
SET name = $3, category_id = $4, active = $5, updated_at = now()
WHERE business_id = $1 AND id = $2
RETURNING id, business_id, category_id, name, active, created_at, updated_at
`

type UpdateProductParams struct {
	BusinessID uuid.UUID   `json:"business_id"`
	ID         uuid.UUID   `json:"id"`
	Name       string      `json:"name"`
	CategoryID pgtype.UUID `json:"category_id"`
	Active     bool        `json:"active"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.BusinessID,
		arg.ID,
		arg.Name,
		arg.CategoryID,
		arg.Active,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.CategoryID,
		&i.Name,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
