// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AcceptInvitation(ctx context.Context, arg AcceptInvitationParams) (Invitation, error)
	ApproveInventoryAdjustmentRequest(ctx context.Context, arg ApproveInventoryAdjustmentRequestParams) (InventoryAdjustmentRequest, error)
	CloseCurrentPrice(ctx context.Context, arg CloseCurrentPriceParams) error
	CountApprovedAdjustmentsByDay(ctx context.Context, arg CountApprovedAdjustmentsByDayParams) ([]CountApprovedAdjustmentsByDayRow, error)
	CountExpensesByDay(ctx context.Context, arg CountExpensesByDayParams) ([]CountExpensesByDayRow, error)
	// The Activity page's GitHub-style daily heatmap needs a per-day count
	// across all four activity sources combined. A single UNION-inside-a-CTE
	// query feeding a GROUP BY/date_trunc aggregate reliably tripped sqlc's
	// static analyzer (a real limitation of the tool, not a Postgres
	// correctness issue -- the same UNION shape runs fine as a plain, non-
	// aggregated SELECT in ListActivity above). Four separate, single-table
	// day-count queries, merged into one day->count map in Go
	// (internal/activity), sidestep it entirely and are individually simpler
	// to read besides.
	CountSalesByDay(ctx context.Context, arg CountSalesByDayParams) ([]CountSalesByDayRow, error)
	CountStockReceiptsByDay(ctx context.Context, arg CountStockReceiptsByDayParams) ([]CountStockReceiptsByDayRow, error)
	CreateBill(ctx context.Context, arg CreateBillParams) (Bill, error)
	CreateBillWriteOff(ctx context.Context, arg CreateBillWriteOffParams) (BillWriteOff, error)
	CreateBusiness(ctx context.Context, arg CreateBusinessParams) (Business, error)
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error)
	CreateDefaultLocation(ctx context.Context, arg CreateDefaultLocationParams) (Location, error)
	CreateDevice(ctx context.Context, arg CreateDeviceParams) (Device, error)
	CreateExpense(ctx context.Context, arg CreateExpenseParams) (Expense, error)
	CreateExpenseCategory(ctx context.Context, arg CreateExpenseCategoryParams) (ExpenseCategory, error)
	CreateIdentityVerification(ctx context.Context, arg CreateIdentityVerificationParams) (IdentityVerification, error)
	CreateInventoryAdjustmentRequest(ctx context.Context, arg CreateInventoryAdjustmentRequestParams) (InventoryAdjustmentRequest, error)
	CreateInventoryEvent(ctx context.Context, arg CreateInventoryEventParams) (InventoryEvent, error)
	CreateInventoryEventForAdjustment(ctx context.Context, arg CreateInventoryEventForAdjustmentParams) (InventoryEvent, error)
	CreateInventoryEventForSale(ctx context.Context, arg CreateInventoryEventForSaleParams) (InventoryEvent, error)
	CreateInventoryMovement(ctx context.Context, arg CreateInventoryMovementParams) (InventoryMovement, error)
	// sale_item_id is only set when this negative_inventory review was opened
	// by a sale's oversell (internal/sales.postSaleRound) -- NULL for one
	// opened by an approved inventory adjustment instead, which has no sale
	// and therefore no pending cost allocation to ever resolve. See
	// docs/PHASE_FIFO_COSTING.md §5.
	CreateInventoryReview(ctx context.Context, arg CreateInventoryReviewParams) (InventoryReview, error)
	CreateInvitation(ctx context.Context, arg CreateInvitationParams) (Invitation, error)
	CreateMembership(ctx context.Context, arg CreateMembershipParams) (BusinessMembership, error)
	CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error)
	CreatePlatformAuditEntry(ctx context.Context, arg CreatePlatformAuditEntryParams) (PlatformAuditLog, error)
	CreatePlatformSession(ctx context.Context, arg CreatePlatformSessionParams) (PlatformSession, error)
	CreatePlatformStaff(ctx context.Context, arg CreatePlatformStaffParams) (PlatformStaff, error)
	CreatePrice(ctx context.Context, arg CreatePriceParams) (ProductPrice, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	CreateSale(ctx context.Context, arg CreateSaleParams) (Sale, error)
	CreateSaleItem(ctx context.Context, arg CreateSaleItemParams) (SaleItem, error)
	CreateSaleItemLotAllocation(ctx context.Context, arg CreateSaleItemLotAllocationParams) (SaleItemLotAllocation, error)
	CreateSaleReview(ctx context.Context, arg CreateSaleReviewParams) (SaleReview, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateStockCount(ctx context.Context, arg CreateStockCountParams) (StockCount, error)
	CreateStockCountLine(ctx context.Context, arg CreateStockCountLineParams) (StockCountLine, error)
	CreateStockLot(ctx context.Context, arg CreateStockLotParams) (StockLot, error)
	CreateStockReceipt(ctx context.Context, arg CreateStockReceiptParams) (StockReceipt, error)
	CreateStockReceiptLine(ctx context.Context, arg CreateStockReceiptLineParams) (StockReceiptLine, error)
	CreateTable(ctx context.Context, arg CreateTableParams) (Table, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateUserIdentity(ctx context.Context, arg CreateUserIdentityParams) (UserIdentity, error)
	CreateVariant(ctx context.Context, arg CreateVariantParams) (ProductVariant, error)
	DecrementLotRemainingQuantity(ctx context.Context, arg DecrementLotRemainingQuantityParams) (StockLot, error)
	DeleteIdentityVerification(ctx context.Context, id uuid.UUID) error
	DeleteSignupVerification(ctx context.Context, id uuid.UUID) error
	GetActiveBillShareLinkByTokenHash(ctx context.Context, tokenHash string) (BillShareLink, error)
	GetActivePlatformSessionByTokenHash(ctx context.Context, tokenHash string) (PlatformSession, error)
	GetActiveSessionByTokenHash(ctx context.Context, tokenHash string) (Session, error)
	GetBillByID(ctx context.Context, arg GetBillByIDParams) (Bill, error)
	GetBillForUpdate(ctx context.Context, arg GetBillForUpdateParams) (Bill, error)
	GetBusinessByID(ctx context.Context, id uuid.UUID) (Business, error)
	GetCategoryByID(ctx context.Context, arg GetCategoryByIDParams) (Category, error)
	GetCategoryByName(ctx context.Context, arg GetCategoryByNameParams) (Category, error)
	GetCurrentPrice(ctx context.Context, arg GetCurrentPriceParams) (ProductPrice, error)
	GetCustomerByID(ctx context.Context, arg GetCustomerByIDParams) (Customer, error)
	GetDefaultLocation(ctx context.Context, businessID uuid.UUID) (Location, error)
	GetDeviceByID(ctx context.Context, arg GetDeviceByIDParams) (Device, error)
	GetExpenseByID(ctx context.Context, arg GetExpenseByIDParams) (Expense, error)
	GetExpenseByIdempotencyKey(ctx context.Context, arg GetExpenseByIdempotencyKeyParams) (Expense, error)
	GetExpenseCategoryByName(ctx context.Context, arg GetExpenseCategoryByNameParams) (ExpenseCategory, error)
	GetIdentityVerificationByID(ctx context.Context, id uuid.UUID) (IdentityVerification, error)
	GetInventoryAdjustmentRequestByIdempotencyKey(ctx context.Context, arg GetInventoryAdjustmentRequestByIdempotencyKeyParams) (InventoryAdjustmentRequest, error)
	// Used to compare a stock count's submitted expected_quantity against the
	// live truth at processing time (docs/PHASE_INVENTORY_COUNTS_AND_
	// ADJUSTMENTS.md: staleness is a value comparison, not a timestamp one).
	// COALESCE to 0 -- a variant with no movements yet simply has no row, not
	// an error (same convention internal/inventory.Service.GetBalances uses).
	GetInventoryBalance(ctx context.Context, arg GetInventoryBalanceParams) (int32, error)
	GetInvitationByID(ctx context.Context, arg GetInvitationByIDParams) (Invitation, error)
	// The public, unauthenticated lookup -- the hashed token is itself the
	// access control (invitations carries no RLS; see migration 000021).
	GetInvitationByTokenHash(ctx context.Context, tokenHash string) (Invitation, error)
	GetLocationByID(ctx context.Context, arg GetLocationByIDParams) (Location, error)
	GetMembership(ctx context.Context, arg GetMembershipParams) (BusinessMembership, error)
	GetPaymentByID(ctx context.Context, arg GetPaymentByIDParams) (Payment, error)
	GetPlatformStaffByEmail(ctx context.Context, email string) (PlatformStaff, error)
	GetPlatformStaffByID(ctx context.Context, id uuid.UUID) (PlatformStaff, error)
	GetPriceAt(ctx context.Context, arg GetPriceAtParams) (ProductPrice, error)
	GetProductByID(ctx context.Context, arg GetProductByIDParams) (Product, error)
	GetReversalOfExpense(ctx context.Context, arg GetReversalOfExpenseParams) (Expense, error)
	GetReversalOfPayment(ctx context.Context, arg GetReversalOfPaymentParams) (Payment, error)
	GetReversalOfSale(ctx context.Context, arg GetReversalOfSaleParams) (Sale, error)
	GetSaleByID(ctx context.Context, arg GetSaleByIDParams) (Sale, error)
	GetSaleByIdempotencyKey(ctx context.Context, arg GetSaleByIdempotencyKeyParams) (Sale, error)
	GetSignupVerificationByEmail(ctx context.Context, email string) (SignupVerification, error)
	GetSignupVerificationByPhone(ctx context.Context, phone pgtype.Text) (SignupVerification, error)
	GetStockCountByIdempotencyKey(ctx context.Context, arg GetStockCountByIdempotencyKeyParams) (StockCount, error)
	GetTableByID(ctx context.Context, arg GetTableByIDParams) (Table, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByPhone(ctx context.Context, phone pgtype.Text) (User, error)
	GetUserIdentity(ctx context.Context, arg GetUserIdentityParams) (UserIdentity, error)
	GetVariantByID(ctx context.Context, arg GetVariantByIDParams) (ProductVariant, error)
	// Joins in the owning product's name for callers that need a full
	// "Product -- Variant" display snapshot (e.g. internal/sales, when
	// recording what was actually sold) -- product_variants.name alone is
	// just the variant's own name ("50cl Bottle"), never the product name.
	GetVariantWithProductNameByID(ctx context.Context, arg GetVariantWithProductNameByIDParams) (GetVariantWithProductNameByIDRow, error)
	// FIFO gross margin (docs/PHASE_FIFO_COSTING.md §8). The allocation_totals
	// CTE pre-aggregates to exactly one row per sale_item BEFORE joining --
	// joining sale_item_lot_allocations directly (one-to-many: a sale
	// spanning two lots, or an oversell, has more than one allocation row per
	// sale_item) would fan out and double-count si.line_total_kobo in the
	// outer SUM, a real bug caught by this query's own test
	// (TestGrossMarginByProductComputesRealCostAndFlagsUnresolvedUnits).
	// revenue_kobo already nets a reversal's negative line totals, same
	// convention SalesByDay relies on; resolved_cogs_kobo nets a reversal's
	// negative allocated_cost rows the same way. unresolved_units is the
	// honesty flag this report exists to never hide: nonzero means some of
	// this product's sold units still have no known cost (an unresolved
	// oversell), so gross_margin (computed in Go as revenue - resolved_cogs)
	// must never be presented as complete while it's nonzero.
	GrossMarginByProduct(ctx context.Context, arg GrossMarginByProductParams) ([]GrossMarginByProductRow, error)
	IncrementIdentityVerificationAttempts(ctx context.Context, id uuid.UUID) error
	IncrementLotRemainingQuantity(ctx context.Context, arg IncrementLotRemainingQuantityParams) (StockLot, error)
	IncrementSignupVerificationAttempts(ctx context.Context, id uuid.UUID) error
	// Unified activity feed (docs/PHASE_EXPENSES_DASHBOARD_ACTIVITY_REPORTS.md
	// §3): a query-time UNION ALL across every domain's own already-posted
	// records, not a new activity_events writer table -- deliberately, same
	// reasoning that kept this codebase off the generic review_cases table
	// and the generic Phase 4 sync protocol. amount_kobo is framed as cash
	// impact (positive = money in, negative = money out) rather than each
	// table's own storage sign convention -- a sale's total_kobo is already
	// money-in-positive, but an expense's amount_kobo (positive = money out
	// by storage convention, negative for its reversal) is flipped here so
	// every row in this feed means the same thing. Every branch aliases its
	// table and qualifies every column (even business_id) explicitly --
	// sqlc's static analyzer otherwise reports a false-positive "business_id
	// is ambiguous" on a UNION ALL of several tables that all happen to carry
	// that column, even though each branch's own FROM is unambiguous under
	// real Postgres.
	ListActivity(ctx context.Context, arg ListActivityParams) ([]ListActivityRow, error)
	ListAllBusinesses(ctx context.Context) ([]Business, error)
	ListAllocationsBySaleItem(ctx context.Context, arg ListAllocationsBySaleItemParams) ([]SaleItemLotAllocation, error)
	ListCatalogueTemplateVariantsByTemplateIDs(ctx context.Context, templateIds []uuid.UUID) ([]CatalogueTemplateVariant, error)
	ListCatalogueTemplates(ctx context.Context) ([]CatalogueTemplate, error)
	ListCatalogueTemplatesByIDs(ctx context.Context, ids []uuid.UUID) ([]CatalogueTemplate, error)
	ListCategories(ctx context.Context, businessID uuid.UUID) ([]Category, error)
	ListCurrentPricesByBusiness(ctx context.Context, businessID uuid.UUID) ([]ProductPrice, error)
	ListCustomers(ctx context.Context, businessID uuid.UUID) ([]Customer, error)
	ListDevicesForBusiness(ctx context.Context, businessID uuid.UUID) ([]Device, error)
	ListExpenseCategories(ctx context.Context, businessID uuid.UUID) ([]ExpenseCategory, error)
	ListExpensesDetailed(ctx context.Context, arg ListExpensesDetailedParams) ([]ListExpensesDetailedRow, error)
	ListInventoryBalances(ctx context.Context, businessID uuid.UUID) ([]InventoryBalance, error)
	// Stock history (docs/PHASE_INVENTORY_COUNTS_AND_ADJUSTMENTS.md §3): a
	// flat, chronological, human-readable feed for one variant -- joins in
	// the event type and, for adjustments, the reason that authorized it.
	ListInventoryMovementsDetailed(ctx context.Context, arg ListInventoryMovementsDetailedParams) ([]ListInventoryMovementsDetailedRow, error)
	ListInvitationsByBusiness(ctx context.Context, businessID uuid.UUID) ([]Invitation, error)
	// FIFO order (docs/PHASE_FIFO_COSTING.md §3): oldest lot first, then lot
	// ID (UUIDv7, itself time-ordered) as a stable tiebreaker for lots
	// received in the same instant. FOR UPDATE is what makes concurrent
	// sales against the same lot actually serialize -- the second
	// transaction blocks until the first commits, then sees the already-
	// decremented remaining_quantity, same locking pattern
	// GetBillForUpdate already established for bill balances.
	ListLotsForAllocation(ctx context.Context, arg ListLotsForAllocationParams) ([]StockLot, error)
	ListMembershipsForUser(ctx context.Context, userID uuid.UUID) ([]ListMembershipsForUserRow, error)
	ListOpenBills(ctx context.Context, businessID uuid.UUID) ([]Bill, error)
	ListOpenInventoryReviewsDetailed(ctx context.Context, businessID uuid.UUID) ([]ListOpenInventoryReviewsDetailedRow, error)
	ListOutstandingBills(ctx context.Context, businessID uuid.UUID) ([]Bill, error)
	ListPaymentsByBillID(ctx context.Context, arg ListPaymentsByBillIDParams) ([]Payment, error)
	ListPendingInventoryAdjustmentRequestsDetailed(ctx context.Context, businessID uuid.UUID) ([]ListPendingInventoryAdjustmentRequestsDetailedRow, error)
	ListPlatformAuditLog(ctx context.Context, limit int32) ([]PlatformAuditLog, error)
	ListPriceHistory(ctx context.Context, arg ListPriceHistoryParams) ([]ProductPrice, error)
	// "Units sold" excludes a reversal's compensating negative-quantity lines
	// -- same reasoning SumSalesTotalSince already applies to sale counts.
	ListProductQuantitiesSold(ctx context.Context, arg ListProductQuantitiesSoldParams) ([]ListProductQuantitiesSoldRow, error)
	ListProducts(ctx context.Context, businessID uuid.UUID) ([]Product, error)
	ListSaleItemsBySaleID(ctx context.Context, arg ListSaleItemsBySaleIDParams) ([]SaleItem, error)
	// Joins in the context a bare sale_reviews row can't give an owner enough
	// to act on: which sale (occurred_at, seller_id) and which item
	// (description, quantity, price). LEFT JOIN on sale_items since
	// sale_reviews.sale_item_id is nullable in schema even though every
	// review created today always populates it.
	ListSaleReviewsDetailed(ctx context.Context, arg ListSaleReviewsDetailedParams) ([]ListSaleReviewsDetailedRow, error)
	ListSales(ctx context.Context, arg ListSalesParams) ([]Sale, error)
	ListSalesByBillID(ctx context.Context, arg ListSalesByBillIDParams) ([]Sale, error)
	ListStaffSales(ctx context.Context, arg ListStaffSalesParams) ([]ListStaffSalesRow, error)
	ListStockCountLines(ctx context.Context, arg ListStockCountLinesParams) ([]StockCountLine, error)
	// Reuses Phase 7's own data directly (docs/PHASE_EXPENSES_DASHBOARD_
	// ACTIVITY_REPORTS.md §3) -- no new schema. A count line's date is its
	// parent count's started_at, since a line itself carries no timestamp.
	ListStockDiscrepancies(ctx context.Context, arg ListStockDiscrepanciesParams) ([]ListStockDiscrepanciesRow, error)
	ListTables(ctx context.Context, businessID uuid.UUID) ([]Table, error)
	ListVariantsByBusiness(ctx context.Context, businessID uuid.UUID) ([]ProductVariant, error)
	ListVariantsByProduct(ctx context.Context, arg ListVariantsByProductParams) ([]ProductVariant, error)
	ListWriteOffsByBillID(ctx context.Context, arg ListWriteOffsByBillIDParams) ([]BillWriteOff, error)
	RejectInventoryAdjustmentRequest(ctx context.Context, arg RejectInventoryAdjustmentRequestParams) (InventoryAdjustmentRequest, error)
	ResolveInventoryReview(ctx context.Context, arg ResolveInventoryReviewParams) (InventoryReview, error)
	ResolveSaleReview(ctx context.Context, arg ResolveSaleReviewParams) (SaleReview, error)
	RevokeBillShareLinkByBillID(ctx context.Context, arg RevokeBillShareLinkByBillIDParams) (BillShareLink, error)
	RevokeDevice(ctx context.Context, arg RevokeDeviceParams) (Device, error)
	RevokeInvitation(ctx context.Context, arg RevokeInvitationParams) (Invitation, error)
	RevokePlatformSession(ctx context.Context, arg RevokePlatformSessionParams) (int64, error)
	RevokeSession(ctx context.Context, arg RevokeSessionParams) (int64, error)
	SetBusinessStatus(ctx context.Context, arg SetBusinessStatusParams) (Business, error)
	SetUserEmail(ctx context.Context, arg SetUserEmailParams) (User, error)
	SetUserPhone(ctx context.Context, arg SetUserPhoneParams) (User, error)
	// Net quantity of one variant currently on a bill, across every round
	// posted so far (a removal round's negative quantity nets against the
	// rounds that added it) -- the cap RemoveBillItem enforces so you can
	// never remove more than is actually there.
	SumBillItemQuantityByVariant(ctx context.Context, arg SumBillItemQuantityByVariantParams) (int32, error)
	SumExpensesByCategory(ctx context.Context, arg SumExpensesByCategoryParams) ([]SumExpensesByCategoryRow, error)
	// Mirrors SumSalesTotalSince exactly: total nets every row including
	// reversals (a reversal's amount_kobo is negative by construction, same
	// sign convention as sales.total_kobo); count excludes reversal rows.
	SumExpensesTotalSince(ctx context.Context, arg SumExpensesTotalSinceParams) (SumExpensesTotalSinceRow, error)
	// Backs the dashboard's "items sold" figure -- excludes a reversal's
	// compensating negative-quantity lines, same reasoning
	// SumSalesTotalSince already applies to its own sale count.
	SumItemsSoldSince(ctx context.Context, arg SumItemsSoldSinceParams) (int64, error)
	// Nets every pending (stock_lot_id IS NULL) allocation for this sale item
	// -- normally just one row, but a resolution's own negative close-out row
	// (docs/PHASE_FIFO_COSTING.md §5) is also stock_lot_id IS NULL, so this
	// must sum rather than assume a single row.
	SumNetPendingQuantityForSaleItem(ctx context.Context, arg SumNetPendingQuantityForSaleItemParams) (int64, error)
	SumPaymentsByBillID(ctx context.Context, arg SumPaymentsByBillIDParams) (int64, error)
	// Backs the Sales report's daily-revenue heatmap (docs/PHASE_EXPENSES_
	// DASHBOARD_ACTIVITY_REPORTS.md §5). Bucketed in the business's own
	// timezone (AT TIME ZONE), not UTC or the caller's -- same reasoning as
	// salesSummary's "today" boundary.
	SumSalesByDay(ctx context.Context, arg SumSalesByDayParams) ([]SumSalesByDayRow, error)
	SumSalesTotalByBillID(ctx context.Context, arg SumSalesTotalByBillIDParams) (int64, error)
	// total nets every row including reversals (a reversal's total_kobo is
	// negative by construction -- see migration 000019); count deliberately
	// excludes reversal rows, since a correction isn't "one more sale" for
	// display purposes.
	SumSalesTotalSince(ctx context.Context, arg SumSalesTotalSinceParams) (SumSalesTotalSinceRow, error)
	// How much was actually spent restocking, per variant, within a range --
	// distinct from GrossMarginByProduct's COGS (only stock that's since been
	// sold) and never counted in the Expenses report (a stock receipt is
	// deliberately not an expense). No fan-out risk: stock_receipt_lines is
	// already one row per variant per receipt, the finest grain here.
	SumStockPurchasesByProduct(ctx context.Context, arg SumStockPurchasesByProductParams) ([]SumStockPurchasesByProductRow, error)
	// Together with SumSalesTotalByBillID and SumPaymentsByBillID (sales minus
	// payments minus write-offs), this is the rebuildable-projection source of
	// truth persisted into bills.balance_kobo by internal/sales.Service.
	SumWriteOffsByBillID(ctx context.Context, arg SumWriteOffsByBillIDParams) (int64, error)
	TouchPlatformSession(ctx context.Context, id uuid.UUID) error
	TouchSession(ctx context.Context, id uuid.UUID) error
	UpdateBillBalanceAndStatus(ctx context.Context, arg UpdateBillBalanceAndStatusParams) (Bill, error)
	UpdateBillStatus(ctx context.Context, arg UpdateBillStatusParams) (Bill, error)
	UpdateBusinessBranding(ctx context.Context, arg UpdateBusinessBrandingParams) (Business, error)
	UpdateBusinessLogo(ctx context.Context, arg UpdateBusinessLogoParams) (Business, error)
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error)
	UpdatePlatformSessionCSRFTokenHash(ctx context.Context, arg UpdatePlatformSessionCSRFTokenHashParams) error
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error)
	UpdateSessionCSRFTokenHash(ctx context.Context, arg UpdateSessionCSRFTokenHashParams) error
	UpdateVariant(ctx context.Context, arg UpdateVariantParams) (ProductVariant, error)
	UpsertBillShareLink(ctx context.Context, arg UpsertBillShareLinkParams) (BillShareLink, error)
	UpsertCatalogueTemplate(ctx context.Context, arg UpsertCatalogueTemplateParams) (CatalogueTemplate, error)
	UpsertCatalogueTemplateVariant(ctx context.Context, arg UpsertCatalogueTemplateVariantParams) (CatalogueTemplateVariant, error)
	UpsertInventoryBalanceDelta(ctx context.Context, arg UpsertInventoryBalanceDeltaParams) (InventoryBalance, error)
	UpsertSignupVerificationByEmail(ctx context.Context, arg UpsertSignupVerificationByEmailParams) (SignupVerification, error)
	UpsertSignupVerificationByPhone(ctx context.Context, arg UpsertSignupVerificationByPhoneParams) (SignupVerification, error)
}

var _ Querier = (*Queries)(nil)
