// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CloseCurrentPrice(ctx context.Context, arg CloseCurrentPriceParams) error
	CreateBusiness(ctx context.Context, arg CreateBusinessParams) (Business, error)
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	CreateDefaultLocation(ctx context.Context, arg CreateDefaultLocationParams) (Location, error)
	CreateDevice(ctx context.Context, arg CreateDeviceParams) (Device, error)
	CreateMembership(ctx context.Context, arg CreateMembershipParams) (BusinessMembership, error)
	CreatePlatformAuditEntry(ctx context.Context, arg CreatePlatformAuditEntryParams) (PlatformAuditLog, error)
	CreatePlatformSession(ctx context.Context, arg CreatePlatformSessionParams) (PlatformSession, error)
	CreatePlatformStaff(ctx context.Context, arg CreatePlatformStaffParams) (PlatformStaff, error)
	CreatePrice(ctx context.Context, arg CreatePriceParams) (ProductPrice, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateUserIdentity(ctx context.Context, arg CreateUserIdentityParams) (UserIdentity, error)
	CreateVariant(ctx context.Context, arg CreateVariantParams) (ProductVariant, error)
	DeleteSignupVerification(ctx context.Context, id uuid.UUID) error
	GetActivePlatformSessionByTokenHash(ctx context.Context, tokenHash string) (PlatformSession, error)
	GetActiveSessionByTokenHash(ctx context.Context, tokenHash string) (Session, error)
	GetBusinessByID(ctx context.Context, id uuid.UUID) (Business, error)
	GetCategoryByID(ctx context.Context, arg GetCategoryByIDParams) (Category, error)
	GetCategoryByName(ctx context.Context, arg GetCategoryByNameParams) (Category, error)
	GetCurrentPrice(ctx context.Context, arg GetCurrentPriceParams) (ProductPrice, error)
	GetDefaultLocation(ctx context.Context, businessID uuid.UUID) (Location, error)
	GetDeviceByID(ctx context.Context, arg GetDeviceByIDParams) (Device, error)
	GetLocationByID(ctx context.Context, arg GetLocationByIDParams) (Location, error)
	GetMembership(ctx context.Context, arg GetMembershipParams) (BusinessMembership, error)
	GetPlatformStaffByEmail(ctx context.Context, email string) (PlatformStaff, error)
	GetPlatformStaffByID(ctx context.Context, id uuid.UUID) (PlatformStaff, error)
	GetProductByID(ctx context.Context, arg GetProductByIDParams) (Product, error)
	GetSignupVerificationByEmail(ctx context.Context, email string) (SignupVerification, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserIdentity(ctx context.Context, arg GetUserIdentityParams) (UserIdentity, error)
	GetVariantByID(ctx context.Context, arg GetVariantByIDParams) (ProductVariant, error)
	IncrementSignupVerificationAttempts(ctx context.Context, id uuid.UUID) error
	ListAllBusinesses(ctx context.Context) ([]Business, error)
	ListCatalogueTemplateVariantsByTemplateIDs(ctx context.Context, templateIds []uuid.UUID) ([]CatalogueTemplateVariant, error)
	ListCatalogueTemplates(ctx context.Context) ([]CatalogueTemplate, error)
	ListCatalogueTemplatesByIDs(ctx context.Context, ids []uuid.UUID) ([]CatalogueTemplate, error)
	ListCategories(ctx context.Context, businessID uuid.UUID) ([]Category, error)
	ListCurrentPricesByBusiness(ctx context.Context, businessID uuid.UUID) ([]ProductPrice, error)
	ListDevicesForBusiness(ctx context.Context, businessID uuid.UUID) ([]Device, error)
	ListMembershipsForUser(ctx context.Context, userID uuid.UUID) ([]ListMembershipsForUserRow, error)
	ListPlatformAuditLog(ctx context.Context, limit int32) ([]PlatformAuditLog, error)
	ListPriceHistory(ctx context.Context, arg ListPriceHistoryParams) ([]ProductPrice, error)
	ListProducts(ctx context.Context, businessID uuid.UUID) ([]Product, error)
	ListVariantsByBusiness(ctx context.Context, businessID uuid.UUID) ([]ProductVariant, error)
	ListVariantsByProduct(ctx context.Context, arg ListVariantsByProductParams) ([]ProductVariant, error)
	RevokeDevice(ctx context.Context, arg RevokeDeviceParams) (Device, error)
	RevokePlatformSession(ctx context.Context, arg RevokePlatformSessionParams) (int64, error)
	RevokeSession(ctx context.Context, arg RevokeSessionParams) (int64, error)
	SetBusinessStatus(ctx context.Context, arg SetBusinessStatusParams) (Business, error)
	TouchPlatformSession(ctx context.Context, id uuid.UUID) error
	TouchSession(ctx context.Context, id uuid.UUID) error
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error)
	UpdatePlatformSessionCSRFTokenHash(ctx context.Context, arg UpdatePlatformSessionCSRFTokenHashParams) error
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error)
	UpdateSessionCSRFTokenHash(ctx context.Context, arg UpdateSessionCSRFTokenHashParams) error
	UpdateVariant(ctx context.Context, arg UpdateVariantParams) (ProductVariant, error)
	UpsertCatalogueTemplate(ctx context.Context, arg UpsertCatalogueTemplateParams) (CatalogueTemplate, error)
	UpsertCatalogueTemplateVariant(ctx context.Context, arg UpsertCatalogueTemplateVariantParams) (CatalogueTemplateVariant, error)
	UpsertSignupVerification(ctx context.Context, arg UpsertSignupVerificationParams) (SignupVerification, error)
}

var _ Querier = (*Queries)(nil)
