// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reports.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const listProductQuantitiesSold = `-- name: ListProductQuantitiesSold :many
SELECT
    si.variant_id, v.name AS variant_name, p.name AS product_name,
    COALESCE(SUM(si.quantity) FILTER (WHERE si.quantity > 0), 0)::bigint AS units_sold
FROM sale_items si
JOIN sales s ON s.business_id = si.business_id AND s.id = si.sale_id
JOIN product_variants v ON v.business_id = si.business_id AND v.id = si.variant_id
JOIN products p ON p.business_id = v.business_id AND p.id = v.product_id
WHERE si.business_id = $1
  AND s.occurred_at >= $2 AND s.occurred_at < $3
GROUP BY si.variant_id, v.name, p.name
ORDER BY units_sold DESC
`

type ListProductQuantitiesSoldParams struct {
	BusinessID   uuid.UUID          `json:"business_id"`
	OccurredAt   pgtype.Timestamptz `json:"occurred_at"`
	OccurredAt_2 pgtype.Timestamptz `json:"occurred_at_2"`
}

type ListProductQuantitiesSoldRow struct {
	VariantID   uuid.UUID `json:"variant_id"`
	VariantName string    `json:"variant_name"`
	ProductName string    `json:"product_name"`
	UnitsSold   int64     `json:"units_sold"`
}

// "Units sold" excludes a reversal's compensating negative-quantity lines
// -- same reasoning SumSalesTotalSince already applies to sale counts.
func (q *Queries) ListProductQuantitiesSold(ctx context.Context, arg ListProductQuantitiesSoldParams) ([]ListProductQuantitiesSoldRow, error) {
	rows, err := q.db.Query(ctx, listProductQuantitiesSold, arg.BusinessID, arg.OccurredAt, arg.OccurredAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProductQuantitiesSoldRow{}
	for rows.Next() {
		var i ListProductQuantitiesSoldRow
		if err := rows.Scan(
			&i.VariantID,
			&i.VariantName,
			&i.ProductName,
			&i.UnitsSold,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaffSales = `-- name: ListStaffSales :many
SELECT
    seller_id,
    COALESCE(SUM(total_kobo), 0)::bigint AS total_kobo,
    COUNT(*) FILTER (WHERE reversal_of_sale_id IS NULL)::bigint AS sale_count
FROM sales
WHERE business_id = $1
  AND occurred_at >= $2 AND occurred_at < $3
GROUP BY seller_id
ORDER BY total_kobo DESC
`

type ListStaffSalesParams struct {
	BusinessID   uuid.UUID          `json:"business_id"`
	OccurredAt   pgtype.Timestamptz `json:"occurred_at"`
	OccurredAt_2 pgtype.Timestamptz `json:"occurred_at_2"`
}

type ListStaffSalesRow struct {
	SellerID  uuid.UUID `json:"seller_id"`
	TotalKobo int64     `json:"total_kobo"`
	SaleCount int64     `json:"sale_count"`
}

func (q *Queries) ListStaffSales(ctx context.Context, arg ListStaffSalesParams) ([]ListStaffSalesRow, error) {
	rows, err := q.db.Query(ctx, listStaffSales, arg.BusinessID, arg.OccurredAt, arg.OccurredAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStaffSalesRow{}
	for rows.Next() {
		var i ListStaffSalesRow
		if err := rows.Scan(&i.SellerID, &i.TotalKobo, &i.SaleCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStockDiscrepancies = `-- name: ListStockDiscrepancies :many
SELECT
    cl.id, cl.count_id, cl.variant_id, cl.expected_quantity, cl.physical_quantity, cl.variance, cl.is_stale,
    sc.started_at, sc.counted_by,
    v.name AS variant_name, p.name AS product_name
FROM stock_count_lines cl
JOIN stock_counts sc ON sc.business_id = cl.business_id AND sc.id = cl.count_id
JOIN product_variants v ON v.business_id = cl.business_id AND v.id = cl.variant_id
JOIN products p ON p.business_id = v.business_id AND p.id = v.product_id
WHERE cl.business_id = $1 AND cl.variance != 0
  AND sc.started_at >= $2 AND sc.started_at < $3
ORDER BY sc.started_at DESC
`

type ListStockDiscrepanciesParams struct {
	BusinessID  uuid.UUID          `json:"business_id"`
	StartedAt   pgtype.Timestamptz `json:"started_at"`
	StartedAt_2 pgtype.Timestamptz `json:"started_at_2"`
}

type ListStockDiscrepanciesRow struct {
	ID               uuid.UUID          `json:"id"`
	CountID          uuid.UUID          `json:"count_id"`
	VariantID        uuid.UUID          `json:"variant_id"`
	ExpectedQuantity int32              `json:"expected_quantity"`
	PhysicalQuantity int32              `json:"physical_quantity"`
	Variance         int32              `json:"variance"`
	IsStale          bool               `json:"is_stale"`
	StartedAt        pgtype.Timestamptz `json:"started_at"`
	CountedBy        uuid.UUID          `json:"counted_by"`
	VariantName      string             `json:"variant_name"`
	ProductName      string             `json:"product_name"`
}

// Reuses Phase 7's own data directly (docs/PHASE_EXPENSES_DASHBOARD_
// ACTIVITY_REPORTS.md §3) -- no new schema. A count line's date is its
// parent count's started_at, since a line itself carries no timestamp.
func (q *Queries) ListStockDiscrepancies(ctx context.Context, arg ListStockDiscrepanciesParams) ([]ListStockDiscrepanciesRow, error) {
	rows, err := q.db.Query(ctx, listStockDiscrepancies, arg.BusinessID, arg.StartedAt, arg.StartedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStockDiscrepanciesRow{}
	for rows.Next() {
		var i ListStockDiscrepanciesRow
		if err := rows.Scan(
			&i.ID,
			&i.CountID,
			&i.VariantID,
			&i.ExpectedQuantity,
			&i.PhysicalQuantity,
			&i.Variance,
			&i.IsStale,
			&i.StartedAt,
			&i.CountedBy,
			&i.VariantName,
			&i.ProductName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumExpensesByCategory = `-- name: SumExpensesByCategory :many
SELECT
    e.category_id, c.name AS category_name,
    COALESCE(SUM(e.amount_kobo), 0)::bigint AS total_kobo,
    COUNT(*) FILTER (WHERE e.reversal_of_expense_id IS NULL)::bigint AS expense_count
FROM expenses e
JOIN expense_categories c ON c.business_id = e.business_id AND c.id = e.category_id
WHERE e.business_id = $1
  AND e.occurred_at >= $2 AND e.occurred_at < $3
GROUP BY e.category_id, c.name
ORDER BY total_kobo DESC
`

type SumExpensesByCategoryParams struct {
	BusinessID   uuid.UUID          `json:"business_id"`
	OccurredAt   pgtype.Timestamptz `json:"occurred_at"`
	OccurredAt_2 pgtype.Timestamptz `json:"occurred_at_2"`
}

type SumExpensesByCategoryRow struct {
	CategoryID   uuid.UUID `json:"category_id"`
	CategoryName string    `json:"category_name"`
	TotalKobo    int64     `json:"total_kobo"`
	ExpenseCount int64     `json:"expense_count"`
}

func (q *Queries) SumExpensesByCategory(ctx context.Context, arg SumExpensesByCategoryParams) ([]SumExpensesByCategoryRow, error) {
	rows, err := q.db.Query(ctx, sumExpensesByCategory, arg.BusinessID, arg.OccurredAt, arg.OccurredAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SumExpensesByCategoryRow{}
	for rows.Next() {
		var i SumExpensesByCategoryRow
		if err := rows.Scan(
			&i.CategoryID,
			&i.CategoryName,
			&i.TotalKobo,
			&i.ExpenseCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumSalesByDay = `-- name: SumSalesByDay :many
SELECT
    date_trunc('day', occurred_at AT TIME ZONE $2::text)::date AS day,
    COALESCE(SUM(total_kobo), 0)::bigint AS total_kobo,
    COUNT(*) FILTER (WHERE reversal_of_sale_id IS NULL)::bigint AS sale_count
FROM sales
WHERE business_id = $1
  AND occurred_at >= $3 AND occurred_at < $4
GROUP BY day
ORDER BY day
`

type SumSalesByDayParams struct {
	BusinessID   uuid.UUID          `json:"business_id"`
	Column2      string             `json:"column_2"`
	OccurredAt   pgtype.Timestamptz `json:"occurred_at"`
	OccurredAt_2 pgtype.Timestamptz `json:"occurred_at_2"`
}

type SumSalesByDayRow struct {
	Day       pgtype.Date `json:"day"`
	TotalKobo int64       `json:"total_kobo"`
	SaleCount int64       `json:"sale_count"`
}

// Backs the Sales report's daily-revenue heatmap (docs/PHASE_EXPENSES_
// DASHBOARD_ACTIVITY_REPORTS.md §5). Bucketed in the business's own
// timezone (AT TIME ZONE), not UTC or the caller's -- same reasoning as
// salesSummary's "today" boundary.
func (q *Queries) SumSalesByDay(ctx context.Context, arg SumSalesByDayParams) ([]SumSalesByDayRow, error) {
	rows, err := q.db.Query(ctx, sumSalesByDay,
		arg.BusinessID,
		arg.Column2,
		arg.OccurredAt,
		arg.OccurredAt_2,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SumSalesByDayRow{}
	for rows.Next() {
		var i SumSalesByDayRow
		if err := rows.Scan(&i.Day, &i.TotalKobo, &i.SaleCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
