// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sales.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createBill = `-- name: CreateBill :one
INSERT INTO bills (id, business_id, location_id, status, opened_by, opened_at, table_id, customer_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, business_id, location_id, status, opened_by, opened_at, created_at, updated_at, table_id, customer_id, balance_kobo
`

type CreateBillParams struct {
	ID         uuid.UUID          `json:"id"`
	BusinessID uuid.UUID          `json:"business_id"`
	LocationID uuid.UUID          `json:"location_id"`
	Status     string             `json:"status"`
	OpenedBy   uuid.UUID          `json:"opened_by"`
	OpenedAt   pgtype.Timestamptz `json:"opened_at"`
	TableID    pgtype.UUID        `json:"table_id"`
	CustomerID pgtype.UUID        `json:"customer_id"`
}

func (q *Queries) CreateBill(ctx context.Context, arg CreateBillParams) (Bill, error) {
	row := q.db.QueryRow(ctx, createBill,
		arg.ID,
		arg.BusinessID,
		arg.LocationID,
		arg.Status,
		arg.OpenedBy,
		arg.OpenedAt,
		arg.TableID,
		arg.CustomerID,
	)
	var i Bill
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.LocationID,
		&i.Status,
		&i.OpenedBy,
		&i.OpenedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TableID,
		&i.CustomerID,
		&i.BalanceKobo,
	)
	return i, err
}

const createInventoryEventForSale = `-- name: CreateInventoryEventForSale :one
INSERT INTO inventory_events (id, business_id, type, actor_id, sale_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, business_id, type, actor_id, receipt_id, occurred_at, created_at, sale_id, adjustment_request_id
`

type CreateInventoryEventForSaleParams struct {
	ID         uuid.UUID   `json:"id"`
	BusinessID uuid.UUID   `json:"business_id"`
	Type       string      `json:"type"`
	ActorID    uuid.UUID   `json:"actor_id"`
	SaleID     pgtype.UUID `json:"sale_id"`
}

func (q *Queries) CreateInventoryEventForSale(ctx context.Context, arg CreateInventoryEventForSaleParams) (InventoryEvent, error) {
	row := q.db.QueryRow(ctx, createInventoryEventForSale,
		arg.ID,
		arg.BusinessID,
		arg.Type,
		arg.ActorID,
		arg.SaleID,
	)
	var i InventoryEvent
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Type,
		&i.ActorID,
		&i.ReceiptID,
		&i.OccurredAt,
		&i.CreatedAt,
		&i.SaleID,
		&i.AdjustmentRequestID,
	)
	return i, err
}

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (id, business_id, bill_id, amount_kobo, method, actor_id, reversal_of_payment_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, business_id, bill_id, amount_kobo, method, actor_id, reversal_of_payment_id, created_at
`

type CreatePaymentParams struct {
	ID                  uuid.UUID   `json:"id"`
	BusinessID          uuid.UUID   `json:"business_id"`
	BillID              uuid.UUID   `json:"bill_id"`
	AmountKobo          int64       `json:"amount_kobo"`
	Method              string      `json:"method"`
	ActorID             uuid.UUID   `json:"actor_id"`
	ReversalOfPaymentID pgtype.UUID `json:"reversal_of_payment_id"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.ID,
		arg.BusinessID,
		arg.BillID,
		arg.AmountKobo,
		arg.Method,
		arg.ActorID,
		arg.ReversalOfPaymentID,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.BillID,
		&i.AmountKobo,
		&i.Method,
		&i.ActorID,
		&i.ReversalOfPaymentID,
		&i.CreatedAt,
	)
	return i, err
}

const createSale = `-- name: CreateSale :one
INSERT INTO sales (id, business_id, bill_id, seller_id, idempotency_key, occurred_at, received_at, total_kobo, reversal_of_sale_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, business_id, bill_id, seller_id, idempotency_key, occurred_at, received_at, total_kobo, reversal_of_sale_id, created_at
`

type CreateSaleParams struct {
	ID               uuid.UUID          `json:"id"`
	BusinessID       uuid.UUID          `json:"business_id"`
	BillID           uuid.UUID          `json:"bill_id"`
	SellerID         uuid.UUID          `json:"seller_id"`
	IdempotencyKey   uuid.UUID          `json:"idempotency_key"`
	OccurredAt       pgtype.Timestamptz `json:"occurred_at"`
	ReceivedAt       pgtype.Timestamptz `json:"received_at"`
	TotalKobo        int64              `json:"total_kobo"`
	ReversalOfSaleID pgtype.UUID        `json:"reversal_of_sale_id"`
}

func (q *Queries) CreateSale(ctx context.Context, arg CreateSaleParams) (Sale, error) {
	row := q.db.QueryRow(ctx, createSale,
		arg.ID,
		arg.BusinessID,
		arg.BillID,
		arg.SellerID,
		arg.IdempotencyKey,
		arg.OccurredAt,
		arg.ReceivedAt,
		arg.TotalKobo,
		arg.ReversalOfSaleID,
	)
	var i Sale
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.BillID,
		&i.SellerID,
		&i.IdempotencyKey,
		&i.OccurredAt,
		&i.ReceivedAt,
		&i.TotalKobo,
		&i.ReversalOfSaleID,
		&i.CreatedAt,
	)
	return i, err
}

const createSaleItem = `-- name: CreateSaleItem :one
INSERT INTO sale_items (id, business_id, sale_id, variant_id, description, quantity, unit_price_kobo, line_total_kobo)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, business_id, sale_id, variant_id, description, quantity, unit_price_kobo, line_total_kobo, created_at
`

type CreateSaleItemParams struct {
	ID            uuid.UUID `json:"id"`
	BusinessID    uuid.UUID `json:"business_id"`
	SaleID        uuid.UUID `json:"sale_id"`
	VariantID     uuid.UUID `json:"variant_id"`
	Description   string    `json:"description"`
	Quantity      int32     `json:"quantity"`
	UnitPriceKobo int64     `json:"unit_price_kobo"`
	LineTotalKobo int64     `json:"line_total_kobo"`
}

func (q *Queries) CreateSaleItem(ctx context.Context, arg CreateSaleItemParams) (SaleItem, error) {
	row := q.db.QueryRow(ctx, createSaleItem,
		arg.ID,
		arg.BusinessID,
		arg.SaleID,
		arg.VariantID,
		arg.Description,
		arg.Quantity,
		arg.UnitPriceKobo,
		arg.LineTotalKobo,
	)
	var i SaleItem
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.SaleID,
		&i.VariantID,
		&i.Description,
		&i.Quantity,
		&i.UnitPriceKobo,
		&i.LineTotalKobo,
		&i.CreatedAt,
	)
	return i, err
}

const createSaleReview = `-- name: CreateSaleReview :one
INSERT INTO sale_reviews (id, business_id, sale_id, sale_item_id, reason)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, business_id, sale_id, sale_item_id, reason, status, resolved_by, resolved_note, resolved_at, created_at
`

type CreateSaleReviewParams struct {
	ID         uuid.UUID   `json:"id"`
	BusinessID uuid.UUID   `json:"business_id"`
	SaleID     uuid.UUID   `json:"sale_id"`
	SaleItemID pgtype.UUID `json:"sale_item_id"`
	Reason     string      `json:"reason"`
}

func (q *Queries) CreateSaleReview(ctx context.Context, arg CreateSaleReviewParams) (SaleReview, error) {
	row := q.db.QueryRow(ctx, createSaleReview,
		arg.ID,
		arg.BusinessID,
		arg.SaleID,
		arg.SaleItemID,
		arg.Reason,
	)
	var i SaleReview
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.SaleID,
		&i.SaleItemID,
		&i.Reason,
		&i.Status,
		&i.ResolvedBy,
		&i.ResolvedNote,
		&i.ResolvedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getBillByID = `-- name: GetBillByID :one
SELECT id, business_id, location_id, status, opened_by, opened_at, created_at, updated_at, table_id, customer_id, balance_kobo FROM bills WHERE business_id = $1 AND id = $2
`

type GetBillByIDParams struct {
	BusinessID uuid.UUID `json:"business_id"`
	ID         uuid.UUID `json:"id"`
}

func (q *Queries) GetBillByID(ctx context.Context, arg GetBillByIDParams) (Bill, error) {
	row := q.db.QueryRow(ctx, getBillByID, arg.BusinessID, arg.ID)
	var i Bill
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.LocationID,
		&i.Status,
		&i.OpenedBy,
		&i.OpenedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TableID,
		&i.CustomerID,
		&i.BalanceKobo,
	)
	return i, err
}

const getReversalOfSale = `-- name: GetReversalOfSale :one
SELECT id, business_id, bill_id, seller_id, idempotency_key, occurred_at, received_at, total_kobo, reversal_of_sale_id, created_at FROM sales WHERE business_id = $1 AND reversal_of_sale_id = $2
`

type GetReversalOfSaleParams struct {
	BusinessID       uuid.UUID   `json:"business_id"`
	ReversalOfSaleID pgtype.UUID `json:"reversal_of_sale_id"`
}

func (q *Queries) GetReversalOfSale(ctx context.Context, arg GetReversalOfSaleParams) (Sale, error) {
	row := q.db.QueryRow(ctx, getReversalOfSale, arg.BusinessID, arg.ReversalOfSaleID)
	var i Sale
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.BillID,
		&i.SellerID,
		&i.IdempotencyKey,
		&i.OccurredAt,
		&i.ReceivedAt,
		&i.TotalKobo,
		&i.ReversalOfSaleID,
		&i.CreatedAt,
	)
	return i, err
}

const getSaleByID = `-- name: GetSaleByID :one
SELECT id, business_id, bill_id, seller_id, idempotency_key, occurred_at, received_at, total_kobo, reversal_of_sale_id, created_at FROM sales WHERE business_id = $1 AND id = $2
`

type GetSaleByIDParams struct {
	BusinessID uuid.UUID `json:"business_id"`
	ID         uuid.UUID `json:"id"`
}

func (q *Queries) GetSaleByID(ctx context.Context, arg GetSaleByIDParams) (Sale, error) {
	row := q.db.QueryRow(ctx, getSaleByID, arg.BusinessID, arg.ID)
	var i Sale
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.BillID,
		&i.SellerID,
		&i.IdempotencyKey,
		&i.OccurredAt,
		&i.ReceivedAt,
		&i.TotalKobo,
		&i.ReversalOfSaleID,
		&i.CreatedAt,
	)
	return i, err
}

const getSaleByIdempotencyKey = `-- name: GetSaleByIdempotencyKey :one
SELECT id, business_id, bill_id, seller_id, idempotency_key, occurred_at, received_at, total_kobo, reversal_of_sale_id, created_at FROM sales WHERE business_id = $1 AND idempotency_key = $2
`

type GetSaleByIdempotencyKeyParams struct {
	BusinessID     uuid.UUID `json:"business_id"`
	IdempotencyKey uuid.UUID `json:"idempotency_key"`
}

func (q *Queries) GetSaleByIdempotencyKey(ctx context.Context, arg GetSaleByIdempotencyKeyParams) (Sale, error) {
	row := q.db.QueryRow(ctx, getSaleByIdempotencyKey, arg.BusinessID, arg.IdempotencyKey)
	var i Sale
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.BillID,
		&i.SellerID,
		&i.IdempotencyKey,
		&i.OccurredAt,
		&i.ReceivedAt,
		&i.TotalKobo,
		&i.ReversalOfSaleID,
		&i.CreatedAt,
	)
	return i, err
}

const listPaymentsByBillID = `-- name: ListPaymentsByBillID :many
SELECT id, business_id, bill_id, amount_kobo, method, actor_id, reversal_of_payment_id, created_at FROM payments WHERE business_id = $1 AND bill_id = $2
`

type ListPaymentsByBillIDParams struct {
	BusinessID uuid.UUID `json:"business_id"`
	BillID     uuid.UUID `json:"bill_id"`
}

func (q *Queries) ListPaymentsByBillID(ctx context.Context, arg ListPaymentsByBillIDParams) ([]Payment, error) {
	rows, err := q.db.Query(ctx, listPaymentsByBillID, arg.BusinessID, arg.BillID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Payment{}
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.BillID,
			&i.AmountKobo,
			&i.Method,
			&i.ActorID,
			&i.ReversalOfPaymentID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSaleItemsBySaleID = `-- name: ListSaleItemsBySaleID :many
SELECT id, business_id, sale_id, variant_id, description, quantity, unit_price_kobo, line_total_kobo, created_at FROM sale_items WHERE business_id = $1 AND sale_id = $2
`

type ListSaleItemsBySaleIDParams struct {
	BusinessID uuid.UUID `json:"business_id"`
	SaleID     uuid.UUID `json:"sale_id"`
}

func (q *Queries) ListSaleItemsBySaleID(ctx context.Context, arg ListSaleItemsBySaleIDParams) ([]SaleItem, error) {
	rows, err := q.db.Query(ctx, listSaleItemsBySaleID, arg.BusinessID, arg.SaleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SaleItem{}
	for rows.Next() {
		var i SaleItem
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.SaleID,
			&i.VariantID,
			&i.Description,
			&i.Quantity,
			&i.UnitPriceKobo,
			&i.LineTotalKobo,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSaleReviewsDetailed = `-- name: ListSaleReviewsDetailed :many
SELECT
    sr.id, sr.sale_id, sr.sale_item_id, sr.reason, sr.status,
    sr.resolved_by, sr.resolved_note, sr.resolved_at, sr.created_at,
    s.occurred_at AS sale_occurred_at, s.seller_id,
    si.description AS item_description, si.quantity AS item_quantity,
    si.unit_price_kobo AS item_unit_price_kobo, si.line_total_kobo AS item_line_total_kobo
FROM sale_reviews sr
JOIN sales s ON s.business_id = sr.business_id AND s.id = sr.sale_id
LEFT JOIN sale_items si ON si.business_id = sr.business_id AND si.id = sr.sale_item_id
WHERE sr.business_id = $1 AND sr.status = $2
ORDER BY sr.created_at DESC
`

type ListSaleReviewsDetailedParams struct {
	BusinessID uuid.UUID `json:"business_id"`
	Status     string    `json:"status"`
}

type ListSaleReviewsDetailedRow struct {
	ID                uuid.UUID          `json:"id"`
	SaleID            uuid.UUID          `json:"sale_id"`
	SaleItemID        pgtype.UUID        `json:"sale_item_id"`
	Reason            string             `json:"reason"`
	Status            string             `json:"status"`
	ResolvedBy        pgtype.UUID        `json:"resolved_by"`
	ResolvedNote      pgtype.Text        `json:"resolved_note"`
	ResolvedAt        pgtype.Timestamptz `json:"resolved_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	SaleOccurredAt    pgtype.Timestamptz `json:"sale_occurred_at"`
	SellerID          uuid.UUID          `json:"seller_id"`
	ItemDescription   pgtype.Text        `json:"item_description"`
	ItemQuantity      pgtype.Int4        `json:"item_quantity"`
	ItemUnitPriceKobo pgtype.Int8        `json:"item_unit_price_kobo"`
	ItemLineTotalKobo pgtype.Int8        `json:"item_line_total_kobo"`
}

// Joins in the context a bare sale_reviews row can't give an owner enough
// to act on: which sale (occurred_at, seller_id) and which item
// (description, quantity, price). LEFT JOIN on sale_items since
// sale_reviews.sale_item_id is nullable in schema even though every
// review created today always populates it.
func (q *Queries) ListSaleReviewsDetailed(ctx context.Context, arg ListSaleReviewsDetailedParams) ([]ListSaleReviewsDetailedRow, error) {
	rows, err := q.db.Query(ctx, listSaleReviewsDetailed, arg.BusinessID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSaleReviewsDetailedRow{}
	for rows.Next() {
		var i ListSaleReviewsDetailedRow
		if err := rows.Scan(
			&i.ID,
			&i.SaleID,
			&i.SaleItemID,
			&i.Reason,
			&i.Status,
			&i.ResolvedBy,
			&i.ResolvedNote,
			&i.ResolvedAt,
			&i.CreatedAt,
			&i.SaleOccurredAt,
			&i.SellerID,
			&i.ItemDescription,
			&i.ItemQuantity,
			&i.ItemUnitPriceKobo,
			&i.ItemLineTotalKobo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSales = `-- name: ListSales :many
SELECT id, business_id, bill_id, seller_id, idempotency_key, occurred_at, received_at, total_kobo, reversal_of_sale_id, created_at FROM sales WHERE business_id = $1 ORDER BY occurred_at DESC LIMIT $2 OFFSET $3
`

type ListSalesParams struct {
	BusinessID uuid.UUID `json:"business_id"`
	Limit      int32     `json:"limit"`
	Offset     int32     `json:"offset"`
}

func (q *Queries) ListSales(ctx context.Context, arg ListSalesParams) ([]Sale, error) {
	rows, err := q.db.Query(ctx, listSales, arg.BusinessID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Sale{}
	for rows.Next() {
		var i Sale
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.BillID,
			&i.SellerID,
			&i.IdempotencyKey,
			&i.OccurredAt,
			&i.ReceivedAt,
			&i.TotalKobo,
			&i.ReversalOfSaleID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveSaleReview = `-- name: ResolveSaleReview :one
UPDATE sale_reviews
    SET status = 'resolved', resolved_by = $3, resolved_note = $4, resolved_at = now()
    WHERE business_id = $1 AND id = $2 AND status = 'open'
RETURNING id, business_id, sale_id, sale_item_id, reason, status, resolved_by, resolved_note, resolved_at, created_at
`

type ResolveSaleReviewParams struct {
	BusinessID   uuid.UUID   `json:"business_id"`
	ID           uuid.UUID   `json:"id"`
	ResolvedBy   pgtype.UUID `json:"resolved_by"`
	ResolvedNote pgtype.Text `json:"resolved_note"`
}

func (q *Queries) ResolveSaleReview(ctx context.Context, arg ResolveSaleReviewParams) (SaleReview, error) {
	row := q.db.QueryRow(ctx, resolveSaleReview,
		arg.BusinessID,
		arg.ID,
		arg.ResolvedBy,
		arg.ResolvedNote,
	)
	var i SaleReview
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.SaleID,
		&i.SaleItemID,
		&i.Reason,
		&i.Status,
		&i.ResolvedBy,
		&i.ResolvedNote,
		&i.ResolvedAt,
		&i.CreatedAt,
	)
	return i, err
}

const sumItemsSoldSince = `-- name: SumItemsSoldSince :one
SELECT COALESCE(SUM(si.quantity) FILTER (WHERE si.quantity > 0), 0)::bigint AS units
FROM sale_items si
JOIN sales s ON s.business_id = si.business_id AND s.id = si.sale_id
WHERE si.business_id = $1 AND s.occurred_at >= $2
`

type SumItemsSoldSinceParams struct {
	BusinessID uuid.UUID          `json:"business_id"`
	OccurredAt pgtype.Timestamptz `json:"occurred_at"`
}

// Backs the dashboard's "items sold" figure -- excludes a reversal's
// compensating negative-quantity lines, same reasoning
// SumSalesTotalSince already applies to its own sale count.
func (q *Queries) SumItemsSoldSince(ctx context.Context, arg SumItemsSoldSinceParams) (int64, error) {
	row := q.db.QueryRow(ctx, sumItemsSoldSince, arg.BusinessID, arg.OccurredAt)
	var units int64
	err := row.Scan(&units)
	return units, err
}

const sumSalesTotalSince = `-- name: SumSalesTotalSince :one
SELECT
    COALESCE(SUM(total_kobo), 0)::bigint AS total,
    COUNT(*) FILTER (WHERE reversal_of_sale_id IS NULL)::bigint AS count
    FROM sales WHERE business_id = $1 AND occurred_at >= $2
`

type SumSalesTotalSinceParams struct {
	BusinessID uuid.UUID          `json:"business_id"`
	OccurredAt pgtype.Timestamptz `json:"occurred_at"`
}

type SumSalesTotalSinceRow struct {
	Total int64 `json:"total"`
	Count int64 `json:"count"`
}

// total nets every row including reversals (a reversal's total_kobo is
// negative by construction -- see migration 000019); count deliberately
// excludes reversal rows, since a correction isn't "one more sale" for
// display purposes.
func (q *Queries) SumSalesTotalSince(ctx context.Context, arg SumSalesTotalSinceParams) (SumSalesTotalSinceRow, error) {
	row := q.db.QueryRow(ctx, sumSalesTotalSince, arg.BusinessID, arg.OccurredAt)
	var i SumSalesTotalSinceRow
	err := row.Scan(&i.Total, &i.Count)
	return i, err
}

const updateBillStatus = `-- name: UpdateBillStatus :one
UPDATE bills SET status = $3, updated_at = now() WHERE business_id = $1 AND id = $2
RETURNING id, business_id, location_id, status, opened_by, opened_at, created_at, updated_at, table_id, customer_id, balance_kobo
`

type UpdateBillStatusParams struct {
	BusinessID uuid.UUID `json:"business_id"`
	ID         uuid.UUID `json:"id"`
	Status     string    `json:"status"`
}

func (q *Queries) UpdateBillStatus(ctx context.Context, arg UpdateBillStatusParams) (Bill, error) {
	row := q.db.QueryRow(ctx, updateBillStatus, arg.BusinessID, arg.ID, arg.Status)
	var i Bill
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.LocationID,
		&i.Status,
		&i.OpenedBy,
		&i.OpenedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TableID,
		&i.CustomerID,
		&i.BalanceKobo,
	)
	return i, err
}
