// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (id, user_id, token_hash, csrf_token_hash, user_agent, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, token_hash, csrf_token_hash, user_agent, created_at, last_used_at, expires_at, revoked_at, revoked_reason
`

type CreateSessionParams struct {
	ID            uuid.UUID          `json:"id"`
	UserID        uuid.UUID          `json:"user_id"`
	TokenHash     string             `json:"token_hash"`
	CsrfTokenHash string             `json:"csrf_token_hash"`
	UserAgent     pgtype.Text        `json:"user_agent"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.CsrfTokenHash,
		arg.UserAgent,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.CsrfTokenHash,
		&i.UserAgent,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RevokedReason,
	)
	return i, err
}

const getActiveSessionByTokenHash = `-- name: GetActiveSessionByTokenHash :one
SELECT id, user_id, token_hash, csrf_token_hash, user_agent, created_at, last_used_at, expires_at, revoked_at, revoked_reason FROM sessions
WHERE token_hash = $1 AND revoked_at IS NULL AND expires_at > now()
`

func (q *Queries) GetActiveSessionByTokenHash(ctx context.Context, tokenHash string) (Session, error) {
	row := q.db.QueryRow(ctx, getActiveSessionByTokenHash, tokenHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.CsrfTokenHash,
		&i.UserAgent,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RevokedReason,
	)
	return i, err
}

const revokeSession = `-- name: RevokeSession :execrows
UPDATE sessions
SET revoked_at = now(), revoked_reason = $2
WHERE id = $1 AND user_id = $3 AND revoked_at IS NULL
`

type RevokeSessionParams struct {
	ID            uuid.UUID   `json:"id"`
	RevokedReason pgtype.Text `json:"revoked_reason"`
	UserID        uuid.UUID   `json:"user_id"`
}

func (q *Queries) RevokeSession(ctx context.Context, arg RevokeSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeSession, arg.ID, arg.RevokedReason, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions SET last_used_at = now() WHERE id = $1
`

func (q *Queries) TouchSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchSession, id)
	return err
}

const updateSessionCSRFTokenHash = `-- name: UpdateSessionCSRFTokenHash :exec
UPDATE sessions SET csrf_token_hash = $2 WHERE id = $1
`

type UpdateSessionCSRFTokenHashParams struct {
	ID            uuid.UUID `json:"id"`
	CsrfTokenHash string    `json:"csrf_token_hash"`
}

func (q *Queries) UpdateSessionCSRFTokenHash(ctx context.Context, arg UpdateSessionCSRFTokenHashParams) error {
	_, err := q.db.Exec(ctx, updateSessionCSRFTokenHash, arg.ID, arg.CsrfTokenHash)
	return err
}
