// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: signup_verifications.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteSignupVerification = `-- name: DeleteSignupVerification :exec
DELETE FROM signup_verifications WHERE id = $1
`

func (q *Queries) DeleteSignupVerification(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSignupVerification, id)
	return err
}

const getSignupVerificationByEmail = `-- name: GetSignupVerificationByEmail :one
SELECT id, email, display_name, password_hash, otp_hash, attempts, expires_at, created_at, updated_at FROM signup_verifications WHERE lower(email) = lower($1)
`

func (q *Queries) GetSignupVerificationByEmail(ctx context.Context, email string) (SignupVerification, error) {
	row := q.db.QueryRow(ctx, getSignupVerificationByEmail, email)
	var i SignupVerification
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.OtpHash,
		&i.Attempts,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementSignupVerificationAttempts = `-- name: IncrementSignupVerificationAttempts :exec
UPDATE signup_verifications SET attempts = attempts + 1, updated_at = now() WHERE id = $1
`

func (q *Queries) IncrementSignupVerificationAttempts(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, incrementSignupVerificationAttempts, id)
	return err
}

const upsertSignupVerification = `-- name: UpsertSignupVerification :one
INSERT INTO signup_verifications (id, email, display_name, password_hash, otp_hash, attempts, expires_at)
VALUES ($1, $2, $3, $4, $5, 0, $6)
ON CONFLICT (lower(email)) DO UPDATE
    SET display_name = EXCLUDED.display_name,
        password_hash = EXCLUDED.password_hash,
        otp_hash = EXCLUDED.otp_hash,
        attempts = 0,
        expires_at = EXCLUDED.expires_at,
        updated_at = now()
RETURNING id, email, display_name, password_hash, otp_hash, attempts, expires_at, created_at, updated_at
`

type UpsertSignupVerificationParams struct {
	ID           uuid.UUID          `json:"id"`
	Email        string             `json:"email"`
	DisplayName  string             `json:"display_name"`
	PasswordHash string             `json:"password_hash"`
	OtpHash      string             `json:"otp_hash"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) UpsertSignupVerification(ctx context.Context, arg UpsertSignupVerificationParams) (SignupVerification, error) {
	row := q.db.QueryRow(ctx, upsertSignupVerification,
		arg.ID,
		arg.Email,
		arg.DisplayName,
		arg.PasswordHash,
		arg.OtpHash,
		arg.ExpiresAt,
	)
	var i SignupVerification
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.OtpHash,
		&i.Attempts,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
