// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tabs.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createBillWriteOff = `-- name: CreateBillWriteOff :one
INSERT INTO bill_write_offs (id, business_id, bill_id, amount_kobo, reason, actor_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, business_id, bill_id, amount_kobo, reason, actor_id, created_at
`

type CreateBillWriteOffParams struct {
	ID         uuid.UUID `json:"id"`
	BusinessID uuid.UUID `json:"business_id"`
	BillID     uuid.UUID `json:"bill_id"`
	AmountKobo int64     `json:"amount_kobo"`
	Reason     string    `json:"reason"`
	ActorID    uuid.UUID `json:"actor_id"`
}

func (q *Queries) CreateBillWriteOff(ctx context.Context, arg CreateBillWriteOffParams) (BillWriteOff, error) {
	row := q.db.QueryRow(ctx, createBillWriteOff,
		arg.ID,
		arg.BusinessID,
		arg.BillID,
		arg.AmountKobo,
		arg.Reason,
		arg.ActorID,
	)
	var i BillWriteOff
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.BillID,
		&i.AmountKobo,
		&i.Reason,
		&i.ActorID,
		&i.CreatedAt,
	)
	return i, err
}

const createCustomer = `-- name: CreateCustomer :one
INSERT INTO customers (id, business_id, name, phone, email, notes)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, business_id, name, phone, email, notes, created_at, updated_at
`

type CreateCustomerParams struct {
	ID         uuid.UUID   `json:"id"`
	BusinessID uuid.UUID   `json:"business_id"`
	Name       string      `json:"name"`
	Phone      pgtype.Text `json:"phone"`
	Email      pgtype.Text `json:"email"`
	Notes      pgtype.Text `json:"notes"`
}

func (q *Queries) CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error) {
	row := q.db.QueryRow(ctx, createCustomer,
		arg.ID,
		arg.BusinessID,
		arg.Name,
		arg.Phone,
		arg.Email,
		arg.Notes,
	)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTable = `-- name: CreateTable :one
INSERT INTO tables (id, business_id, label)
VALUES ($1, $2, $3)
RETURNING id, business_id, label, active, created_at
`

type CreateTableParams struct {
	ID         uuid.UUID `json:"id"`
	BusinessID uuid.UUID `json:"business_id"`
	Label      string    `json:"label"`
}

func (q *Queries) CreateTable(ctx context.Context, arg CreateTableParams) (Table, error) {
	row := q.db.QueryRow(ctx, createTable, arg.ID, arg.BusinessID, arg.Label)
	var i Table
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Label,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const getBillForUpdate = `-- name: GetBillForUpdate :one
SELECT id, business_id, location_id, status, opened_by, opened_at, created_at, updated_at, table_id, customer_id, balance_kobo FROM bills WHERE business_id = $1 AND id = $2 FOR UPDATE
`

type GetBillForUpdateParams struct {
	BusinessID uuid.UUID `json:"business_id"`
	ID         uuid.UUID `json:"id"`
}

func (q *Queries) GetBillForUpdate(ctx context.Context, arg GetBillForUpdateParams) (Bill, error) {
	row := q.db.QueryRow(ctx, getBillForUpdate, arg.BusinessID, arg.ID)
	var i Bill
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.LocationID,
		&i.Status,
		&i.OpenedBy,
		&i.OpenedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TableID,
		&i.CustomerID,
		&i.BalanceKobo,
	)
	return i, err
}

const getCustomerByID = `-- name: GetCustomerByID :one
SELECT id, business_id, name, phone, email, notes, created_at, updated_at FROM customers WHERE business_id = $1 AND id = $2
`

type GetCustomerByIDParams struct {
	BusinessID uuid.UUID `json:"business_id"`
	ID         uuid.UUID `json:"id"`
}

func (q *Queries) GetCustomerByID(ctx context.Context, arg GetCustomerByIDParams) (Customer, error) {
	row := q.db.QueryRow(ctx, getCustomerByID, arg.BusinessID, arg.ID)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentByID = `-- name: GetPaymentByID :one
SELECT id, business_id, bill_id, amount_kobo, method, actor_id, reversal_of_payment_id, created_at FROM payments WHERE business_id = $1 AND id = $2
`

type GetPaymentByIDParams struct {
	BusinessID uuid.UUID `json:"business_id"`
	ID         uuid.UUID `json:"id"`
}

func (q *Queries) GetPaymentByID(ctx context.Context, arg GetPaymentByIDParams) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByID, arg.BusinessID, arg.ID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.BillID,
		&i.AmountKobo,
		&i.Method,
		&i.ActorID,
		&i.ReversalOfPaymentID,
		&i.CreatedAt,
	)
	return i, err
}

const getReversalOfPayment = `-- name: GetReversalOfPayment :one
SELECT id, business_id, bill_id, amount_kobo, method, actor_id, reversal_of_payment_id, created_at FROM payments WHERE business_id = $1 AND reversal_of_payment_id = $2
`

type GetReversalOfPaymentParams struct {
	BusinessID          uuid.UUID   `json:"business_id"`
	ReversalOfPaymentID pgtype.UUID `json:"reversal_of_payment_id"`
}

func (q *Queries) GetReversalOfPayment(ctx context.Context, arg GetReversalOfPaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, getReversalOfPayment, arg.BusinessID, arg.ReversalOfPaymentID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.BillID,
		&i.AmountKobo,
		&i.Method,
		&i.ActorID,
		&i.ReversalOfPaymentID,
		&i.CreatedAt,
	)
	return i, err
}

const getTableByID = `-- name: GetTableByID :one
SELECT id, business_id, label, active, created_at FROM tables WHERE business_id = $1 AND id = $2
`

type GetTableByIDParams struct {
	BusinessID uuid.UUID `json:"business_id"`
	ID         uuid.UUID `json:"id"`
}

func (q *Queries) GetTableByID(ctx context.Context, arg GetTableByIDParams) (Table, error) {
	row := q.db.QueryRow(ctx, getTableByID, arg.BusinessID, arg.ID)
	var i Table
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Label,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const listCustomers = `-- name: ListCustomers :many
SELECT id, business_id, name, phone, email, notes, created_at, updated_at FROM customers WHERE business_id = $1 ORDER BY name
`

func (q *Queries) ListCustomers(ctx context.Context, businessID uuid.UUID) ([]Customer, error) {
	rows, err := q.db.Query(ctx, listCustomers, businessID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Customer{}
	for rows.Next() {
		var i Customer
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.Name,
			&i.Phone,
			&i.Email,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenBills = `-- name: ListOpenBills :many
SELECT id, business_id, location_id, status, opened_by, opened_at, created_at, updated_at, table_id, customer_id, balance_kobo FROM bills WHERE business_id = $1 AND status IN ('open', 'closed_unpaid') ORDER BY opened_at
`

func (q *Queries) ListOpenBills(ctx context.Context, businessID uuid.UUID) ([]Bill, error) {
	rows, err := q.db.Query(ctx, listOpenBills, businessID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Bill{}
	for rows.Next() {
		var i Bill
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.LocationID,
			&i.Status,
			&i.OpenedBy,
			&i.OpenedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TableID,
			&i.CustomerID,
			&i.BalanceKobo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOutstandingBills = `-- name: ListOutstandingBills :many
SELECT id, business_id, location_id, status, opened_by, opened_at, created_at, updated_at, table_id, customer_id, balance_kobo FROM bills WHERE business_id = $1 AND balance_kobo <> 0 ORDER BY opened_at
`

func (q *Queries) ListOutstandingBills(ctx context.Context, businessID uuid.UUID) ([]Bill, error) {
	rows, err := q.db.Query(ctx, listOutstandingBills, businessID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Bill{}
	for rows.Next() {
		var i Bill
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.LocationID,
			&i.Status,
			&i.OpenedBy,
			&i.OpenedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TableID,
			&i.CustomerID,
			&i.BalanceKobo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSalesByBillID = `-- name: ListSalesByBillID :many
SELECT id, business_id, bill_id, seller_id, idempotency_key, occurred_at, received_at, total_kobo, reversal_of_sale_id, created_at FROM sales WHERE business_id = $1 AND bill_id = $2 ORDER BY occurred_at
`

type ListSalesByBillIDParams struct {
	BusinessID uuid.UUID `json:"business_id"`
	BillID     uuid.UUID `json:"bill_id"`
}

func (q *Queries) ListSalesByBillID(ctx context.Context, arg ListSalesByBillIDParams) ([]Sale, error) {
	rows, err := q.db.Query(ctx, listSalesByBillID, arg.BusinessID, arg.BillID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Sale{}
	for rows.Next() {
		var i Sale
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.BillID,
			&i.SellerID,
			&i.IdempotencyKey,
			&i.OccurredAt,
			&i.ReceivedAt,
			&i.TotalKobo,
			&i.ReversalOfSaleID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTables = `-- name: ListTables :many
SELECT id, business_id, label, active, created_at FROM tables WHERE business_id = $1 AND active = true ORDER BY label
`

func (q *Queries) ListTables(ctx context.Context, businessID uuid.UUID) ([]Table, error) {
	rows, err := q.db.Query(ctx, listTables, businessID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Table{}
	for rows.Next() {
		var i Table
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.Label,
			&i.Active,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWriteOffsByBillID = `-- name: ListWriteOffsByBillID :many
SELECT id, business_id, bill_id, amount_kobo, reason, actor_id, created_at FROM bill_write_offs WHERE business_id = $1 AND bill_id = $2 ORDER BY created_at
`

type ListWriteOffsByBillIDParams struct {
	BusinessID uuid.UUID `json:"business_id"`
	BillID     uuid.UUID `json:"bill_id"`
}

func (q *Queries) ListWriteOffsByBillID(ctx context.Context, arg ListWriteOffsByBillIDParams) ([]BillWriteOff, error) {
	rows, err := q.db.Query(ctx, listWriteOffsByBillID, arg.BusinessID, arg.BillID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BillWriteOff{}
	for rows.Next() {
		var i BillWriteOff
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.BillID,
			&i.AmountKobo,
			&i.Reason,
			&i.ActorID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumBillItemQuantityByVariant = `-- name: SumBillItemQuantityByVariant :one
SELECT COALESCE(SUM(sale_items.quantity), 0)::int AS quantity
FROM sale_items
JOIN sales ON sales.business_id = sale_items.business_id AND sales.id = sale_items.sale_id
WHERE sale_items.business_id = $1 AND sales.bill_id = $2 AND sale_items.variant_id = $3
`

type SumBillItemQuantityByVariantParams struct {
	BusinessID uuid.UUID `json:"business_id"`
	BillID     uuid.UUID `json:"bill_id"`
	VariantID  uuid.UUID `json:"variant_id"`
}

// Net quantity of one variant currently on a bill, across every round
// posted so far (a removal round's negative quantity nets against the
// rounds that added it) -- the cap RemoveBillItem enforces so you can
// never remove more than is actually there.
func (q *Queries) SumBillItemQuantityByVariant(ctx context.Context, arg SumBillItemQuantityByVariantParams) (int32, error) {
	row := q.db.QueryRow(ctx, sumBillItemQuantityByVariant, arg.BusinessID, arg.BillID, arg.VariantID)
	var quantity int32
	err := row.Scan(&quantity)
	return quantity, err
}

const sumPaymentsByBillID = `-- name: SumPaymentsByBillID :one
SELECT COALESCE(SUM(amount_kobo), 0)::bigint AS total FROM payments WHERE business_id = $1 AND bill_id = $2
`

type SumPaymentsByBillIDParams struct {
	BusinessID uuid.UUID `json:"business_id"`
	BillID     uuid.UUID `json:"bill_id"`
}

func (q *Queries) SumPaymentsByBillID(ctx context.Context, arg SumPaymentsByBillIDParams) (int64, error) {
	row := q.db.QueryRow(ctx, sumPaymentsByBillID, arg.BusinessID, arg.BillID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const sumSalesTotalByBillID = `-- name: SumSalesTotalByBillID :one
SELECT COALESCE(SUM(total_kobo), 0)::bigint AS total FROM sales WHERE business_id = $1 AND bill_id = $2
`

type SumSalesTotalByBillIDParams struct {
	BusinessID uuid.UUID `json:"business_id"`
	BillID     uuid.UUID `json:"bill_id"`
}

func (q *Queries) SumSalesTotalByBillID(ctx context.Context, arg SumSalesTotalByBillIDParams) (int64, error) {
	row := q.db.QueryRow(ctx, sumSalesTotalByBillID, arg.BusinessID, arg.BillID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const sumWriteOffsByBillID = `-- name: SumWriteOffsByBillID :one
SELECT COALESCE(SUM(amount_kobo), 0)::bigint AS total FROM bill_write_offs WHERE business_id = $1 AND bill_id = $2
`

type SumWriteOffsByBillIDParams struct {
	BusinessID uuid.UUID `json:"business_id"`
	BillID     uuid.UUID `json:"bill_id"`
}

// Together with SumSalesTotalByBillID and SumPaymentsByBillID (sales minus
// payments minus write-offs), this is the rebuildable-projection source of
// truth persisted into bills.balance_kobo by internal/sales.Service.
func (q *Queries) SumWriteOffsByBillID(ctx context.Context, arg SumWriteOffsByBillIDParams) (int64, error) {
	row := q.db.QueryRow(ctx, sumWriteOffsByBillID, arg.BusinessID, arg.BillID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const updateBillBalanceAndStatus = `-- name: UpdateBillBalanceAndStatus :one
UPDATE bills SET balance_kobo = $3, status = $4, updated_at = now()
    WHERE business_id = $1 AND id = $2
RETURNING id, business_id, location_id, status, opened_by, opened_at, created_at, updated_at, table_id, customer_id, balance_kobo
`

type UpdateBillBalanceAndStatusParams struct {
	BusinessID  uuid.UUID `json:"business_id"`
	ID          uuid.UUID `json:"id"`
	BalanceKobo int64     `json:"balance_kobo"`
	Status      string    `json:"status"`
}

func (q *Queries) UpdateBillBalanceAndStatus(ctx context.Context, arg UpdateBillBalanceAndStatusParams) (Bill, error) {
	row := q.db.QueryRow(ctx, updateBillBalanceAndStatus,
		arg.BusinessID,
		arg.ID,
		arg.BalanceKobo,
		arg.Status,
	)
	var i Bill
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.LocationID,
		&i.Status,
		&i.OpenedBy,
		&i.OpenedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TableID,
		&i.CustomerID,
		&i.BalanceKobo,
	)
	return i, err
}
